import { z } from 'zod';
import {docxMime} from '../media/schema.js';
import { money, menuSchema, menuInputSchema, orderStatusSchema } from '../food/schema.js';
import type { AnyOrder } from '../orders/schema.js';
export const listQuery = z.strictObject({ city_id: z.uuid().optional(), status: orderStatusSchema.optional(), limit: z.coerce.number().int().min(1).max(100).default(50), offset: z.coerce.number().int().min(0).max(10000).default(0) });
export type ListQuery = z.infer<typeof listQuery>;
export const cityInput = z.strictObject({ is_active: z.boolean(), base_fare_kobo: money, per_km_rate_kobo: money, minimum_delivery_fee_kobo: money, minimum_food_subtotal_kobo: money, opens_at: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$/).nullable(), closes_at: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$/).nullable(), surge_bps: z.number().int().min(10000).max(50000) }).refine(v => (v.opens_at === null) === (v.closes_at === null), 'Configure both hours.');
export type CityInput = z.infer<typeof cityInput>;
export const adminCitySchema = z.object({ ...cityInput.shape, base_fare_kobo: money.nullable(), per_km_rate_kobo: money.nullable(), id: z.uuid(), name: z.string() });
export const documentInput = z.strictObject({ kind: z.enum(['identity', 'license', 'vehicle', 'insurance']), mime: z.enum(['image/jpeg', 'image/png', 'application/pdf',docxMime]), data_base64: z.string().min(4).max(2796204) });
export type DocumentInput = z.infer<typeof documentInput>;
export const documentSchema = z.object({ ...documentInput.omit({ data_base64: true }).shape, id: z.uuid(), rider_id: z.uuid(), bytes: z.number().int(), sha256: z.string(), status: z.enum(['pending', 'approved', 'rejected']), review_note: z.string().nullable(), created_at: z.string(), reviewed_at: z.string().nullable() });
export const tierInput = z.strictObject({ name: z.string().trim().min(2).max(80), active: z.boolean(), placement_rank: z.number().int().min(0).max(100), commission_bps: z.number().int().min(0).max(10000).nullable() });
export type TierInput = z.infer<typeof tierInput>;
export const tierSchema = z.object({ ...tierInput.shape, id: z.uuid() });
export const membershipInput = z.strictObject({ tier_id: z.uuid(), starts_at: z.iso.datetime({ offset: true }), ends_at: z.iso.datetime({ offset: true }) }).refine(v => Date.parse(v.ends_at) > Date.parse(v.starts_at), 'Invalid dates.');
export type MembershipInput = z.infer<typeof membershipInput>;
export const bannerInput = z.strictObject({ city_id: z.uuid().nullable(), title: z.string().trim().min(2).max(120), body: z.string().trim().max(500), image_url: z.url().refine(v => new URL(v).protocol === 'https:').nullable(), action: z.enum(['food', 'dispatch', 'wallet', 'vendor']), vendor_id: z.uuid().nullable(), starts_at: z.iso.datetime({ offset: true }), ends_at: z.iso.datetime({ offset: true }), active: z.boolean(), priority: z.number().int().min(0).max(100) }).refine(v => Date.parse(v.ends_at) > Date.parse(v.starts_at), 'Invalid dates.').refine(v => (v.action === 'vendor') === (v.vendor_id !== null), 'Vendor action requires a vendor.');
export type BannerInput = z.infer<typeof bannerInput>;
export const bannerSchema = z.object({ ...bannerInput.shape, id: z.uuid() });
export const reportQuery = z.strictObject({ from: z.iso.datetime({ offset: true }), to: z.iso.datetime({ offset: true }), city_id: z.uuid().optional() }).refine(v => Date.parse(v.to) > Date.parse(v.from) && Date.parse(v.to) - Date.parse(v.from) <= 90 * 86400000, 'Choose a window up to 90 days.');
export type ReportQuery = z.infer<typeof reportQuery>;
export const reportRow = z.object({ day: z.string(), city_id: z.uuid(), type: z.enum(['food', 'dispatch']), orders: z.number().int(), paid_orders: z.number().int(), delivered: z.number().int(), cancelled: z.number().int(), paid_kobo: z.number().int(), refunded_kobo: z.number().int(), avg_delivery_seconds: z.number().nullable() });
export const riderListSchema = z.object({ id: z.uuid(), name: z.string(), city_id: z.uuid(), approval: z.string(), online: z.boolean(), vehicle_type: z.string(), plate_number: z.string(), lat: z.number().nullable(), lng: z.number().nullable(), captured_at: z.string().nullable(), location_stale: z.boolean() });
export const auditSchema = z.object({ id: z.uuid(), actor_id: z.uuid(), action: z.string(), target_id: z.uuid(), created_at: z.string() });
export const healthSchema = z.object({ orders_waiting: z.number().int(), offers_pending: z.number().int(), notifications_pending: z.number().int(), notifications_failed: z.number().int(), withdrawals_review: z.number().int(), unsettled_deliveries: z.number().int(), workers: z.array(z.object({ kind: z.string(), last_success_at: z.string().nullable(), last_failure_at: z.string().nullable(), last_duration_ms: z.number().int() })) });
export const placementSchema = z.object({ vendor_id: z.uuid(), name: z.string(), tier: z.string(), placement_rank: z.number().int(), sponsored: z.literal(true) });
export interface OperationsRepository {
    adminOrders(actor: string, input: ListQuery): Promise<AnyOrder[]>;
    adminOrder(actor: string, id: string): Promise<AnyOrder>;
    cities(actor: string): Promise<z.infer<typeof adminCitySchema>[]>;
    saveCity(actor: string, id: string, input: CityInput): Promise<z.infer<typeof adminCitySchema>>;
    riders(actor: string, city: string | undefined, limit: number, offset: number): Promise<z.infer<typeof riderListSchema>[]>;
    reassign(actor: string, id: string, rider: string, reason: string): Promise<AnyOrder>;
    cancel(actor: string, id: string, reason: string): Promise<AnyOrder>;
    custody(actor: string, id: string, outcome: 'delivered' | 'cancelled', reason: string): Promise<AnyOrder>;
    vendorOrders(actor: string, vendor: string, limit: number, offset: number): Promise<AnyOrder[]>;
    vendorMenu(actor: string, vendor: string): Promise<z.infer<typeof menuSchema>[]>;
    saveMenu(actor: string, vendor: string, item: string | undefined, input: z.infer<typeof menuInputSchema>): Promise<z.infer<typeof menuSchema>>;
    vendorOpen(actor: string, vendor: string, open: boolean): Promise<void>;
    documents(actor: string, rider: string): Promise<z.infer<typeof documentSchema>[]>;
    upload(actor: string, input: DocumentInput): Promise<z.infer<typeof documentSchema>>;
    document(actor: string, id: string): Promise<{
        mime: string;
        data_base64: string;
    }>;
    reviewDocument(actor: string, id: string, status: 'approved' | 'rejected', note: string): Promise<void>;
    saveTier(actor: string, input: TierInput, id?: string): Promise<z.infer<typeof tierSchema>>;
    tiers(actor: string): Promise<z.infer<typeof tierSchema>[]>;
    membership(actor: string, vendor: string, input: MembershipInput): Promise<void>;
    saveBanner(actor: string, input: BannerInput, id?: string): Promise<z.infer<typeof bannerSchema>>;
    banners(city: string): Promise<z.infer<typeof bannerSchema>[]>;
    placements(city: string): Promise<z.infer<typeof placementSchema>[]>;
    report(actor: string, input: ReportQuery): Promise<z.infer<typeof reportRow>[]>;
    audits(actor: string, limit: number, offset: number): Promise<z.infer<typeof auditSchema>[]>;
    health(actor: string): Promise<z.infer<typeof healthSchema>>;
    heartbeat(kind: string, success: boolean, duration: number): Promise<void>;
}
