import type { ImgHTMLAttributes } from "react";

type Props = ImgHTMLAttributes<HTMLImageElement> & { src: string; darkSrc?: string | null };

/**
 * An image with a light and a dark version; CSS shows the one matching [data-theme].
 * Illustrations get their dark twin automatically (x.svg -> x-dark.svg, generated by
 * scripts/illustrations.py). The CTA scene is already a night scene, so it has none.
 */
export function Art({ src, darkSrc, className, alt = "", ...rest }: Props) {
  const dark =
    darkSrc !== undefined
      ? darkSrc
      : src.startsWith("/illustrations/") && !src.includes("cta-scene")
        ? src.replace(/\.svg$/, "-dark.svg")
        : null;
  const cls = (theme: string) => [className, theme].filter(Boolean).join(" ");

  if (!dark) return <img src={src} className={className} alt={alt} {...rest} />;
  return (
    <>
      <img src={src} className={cls("only-light")} alt={alt} {...rest} />
      <img src={dark} className={cls("only-dark")} alt={alt} {...rest} />
    </>
  );
}
