"use client";
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {request} from '@/api/client';
import type {Row} from '@/api/types';
import {Workbench,field,money,note,reason,rowId,type Action,type Field} from './Workbench';
import {Button,Spinner} from './ui';
import {RiderDocuments} from './RiderDocuments';
const idPath=(suffix:string)=>(r:Row)=>`/v1/admin/orders/${rowId(r)}/${suffix}`;
const reviewFields=[field('decision','Decision','select',{options:['approve','reject']}),note];
const vendorFields=[field('name','Store name'),field('category','Category','select',{options:['restaurant','fast_food','drinks','groceries','pharmacy']}),field('city_id','Service city ID'),field('address','Pickup address'),field('lat','Latitude','number',{min:-90,max:90}),field('lng','Longitude','number',{min:-180,max:180})];
// Full store input: coordinate fields become the backend location object.
const storeFields:Field[]=[...vendorFields.slice(0,6),field('cuisine','Cuisine','text',{optional:true}),field('prep_minutes','Preparation minutes','number',{min:1,max:180}),field('is_open','Open for orders','boolean'),field('is_active','Active store','boolean'),field('image_url','Banner HTTPS URL','text',{nullable:true})];
const storeTransform=(v:Row)=>{const {lat,lng,...rest}=v;return {...rest,location:{lat,lng}};};
const storeInitial=(r:Row)=>({...r,lat:r.latitude,lng:r.longitude,...(r.location as Row??{})});
export function OrdersPage(){return <Workbench datasets={[{label:'Orders',path:'/v1/admin/orders',columns:['code','type','status','payment_status','payment_method','refund_status','created_at'],actions:[
 {label:'Reassign rider',path:idPath('reassign'),fields:[field('rider_id','Eligible rider profile ID'),reason],show:r=>['awaiting_vendor','searching_rider','rider_assigned'].includes(String(r.status))},
 {label:'Cancel order',path:idPath('cancel'),fields:[reason],danger:true,show:r=>!['picked_up','on_the_way','delivered','cancelled','disputed'].includes(String(r.status)),detail:'Paid cancellations create a refund request. External refunds require provider reconciliation.'},
 {label:'Resolve dispute',path:idPath('dispute/resolve'),fields:[field('resolution','Resolution (at least 10 characters)')],show:r=>r.status==='disputed'},
 {label:'Resolve custody',path:idPath('custody-resolution'),fields:[field('outcome','Outcome','select',{options:['delivered','cancelled']}),field('reason','Evidence and reason (at least 20 characters)'),field('custody_confirmed','Physical custody has been confirmed','boolean')],danger:true,show:r=>['picked_up','on_the_way','disputed'].includes(String(r.status))}
 ]}]} detail={r=><Workbench datasets={[{label:'Timeline',resource:'events',id:rowId(r),columns:['from_status','to_status','reason','created_at']}]} />}/>;}
const adjustment=(kind:'customer'|'rider'):Action=>({label:'Adjust balance',path:'/v1/admin/balances/adjust',fields:[field('amount_kobo','Signed adjustment in kobo (negative to debit)','number',{min:-1000000000,max:1000000000}),reason],transform:(v,r)=>({...v,kind,id:String(r.profile_id??r.id)}),danger:true,detail:'Creates an immutable ledger entry. Debit cannot exceed available funds; held earnings are unchanged.'});
export function CustomersPage(){return <Workbench datasets={[{label:'Customers',resource:'customers',columns:['name','email','phone','status','orders','paid_total_kobo','wallet_kobo','created_at'],actions:[adjustment('customer')]}]}/>;}
export function RidersPage(){return <Workbench description="Click a rider to see their documents and last location. Every document must be approved before the rider can be." datasets={[{label:'Riders',resource:'riders',columns:['name','phone','city_id','approval','online','trips','available_kobo','lat','lng','captured_at','location_stale'],actions:[{label:'Review rider',path:r=>`/v1/admin/riders/${r.profile_id}/review`,fields:[field('approval','Approval','select',{options:['approved','rejected','suspended']}),note],detail:'Before approving, every document must be approved: close this, click the rider’s row to open their details, and use View / Approve under Documents.'},adjustment('rider')]}]} detail={r=><div className="stack">{r.lat!=null&&r.lng!=null?<a className="text-primary" href={`https://www.google.com/maps?q=${r.lat},${r.lng}`} target="_blank" rel="noopener noreferrer">View last recorded location on map{r.location_stale?' (stale)':''}</a>:<p>No location recorded.</p>}<RiderDocuments riderId={String(r.profile_id)}/></div>}/>;}
const menuFields=[field('name','Item name'),field('description','Description','text',{optional:true}),money('price_kobo','Price'),field('category','Menu category'),field('is_available','Available','boolean'),field('image_url','HTTPS image URL','text',{nullable:true}),field('option_groups','Option groups JSON','json',{value:'[]'})];
const tierFields=[field('name','Tier name'),field('active','Active','boolean'),field('placement_rank','Placement rank','number',{min:0,max:100}),field('commission_bps','Commission basis points','number',{nullable:true,min:0,max:10000})];
export function VendorsPage(){return <Workbench description="Applications are private submissions; approving creates the store and links its owner. Existing stores are managed separately." datasets={[
 {label:'Stores',resource:'vendors',columns:['name','category','city_id','is_active','is_open','rating','menu_items','delivered_30d','sales_30d_kobo'],create:{label:'Add store',path:'/v1/admin/vendors',fields:storeFields,transform:storeTransform},actions:[{label:'Edit store',path:r=>`/v1/admin/vendors/${rowId(r)}`,method:'PUT',fields:storeFields,initial:storeInitial,transform:storeTransform},{label:'Change store status',path:r=>`/v1/admin/vendors/${rowId(r)}/status`,fields:[field('is_active','Active','boolean'),reason],danger:true},{label:'Assign staff',path:r=>`/v1/admin/vendors/${rowId(r)}/staff`,fields:[field('profile_id','Existing staff profile ID')]},{label:'Assign membership',path:r=>`/v1/admin/vendors/${rowId(r)}/membership`,method:'PUT',fields:[field('tier_id','Tier ID'),field('starts_at','Starts','datetime-local'),field('ends_at','Ends','datetime-local')]}]},
 {label:'Applications',path:'/v1/admin/vendor-applications',columns:['id','profile_id','status','input','review_note','created_at'],actions:[{label:'Review application',path:r=>`/v1/admin/vendor-applications/${rowId(r)}/review`,fields:reviewFields,show:r=>r.status==='pending'}]},
 {label:'Membership tiers',path:'/v1/admin/membership-tiers',columns:['id','name','active','placement_rank','commission_bps'],create:{label:'Create tier',path:'/v1/admin/membership-tiers',fields:tierFields},actions:[{label:'Edit tier',path:r=>`/v1/admin/membership-tiers/${rowId(r)}`,method:'PUT',fields:tierFields}]}
 ]} detail={(r,tab)=>tab.resource==='vendors'?<Workbench datasets={[{label:'Menu',resource:'menu',id:rowId(r),columns:['name','category','price_kobo','is_available','image_url'],create:{label:'Add menu item',path:`/v1/admin/vendors/${rowId(r)}/menu`,fields:menuFields},actions:[{label:'Edit menu item',path:m=>`/v1/admin/vendors/${rowId(r)}/menu/${rowId(m)}`,method:'PUT',fields:menuFields}]}]}/>:null}/>;}
export function PaymentsPage(){return <Workbench description="All amounts are kobo. Withdrawal approval queues a transfer; it does not mean the bank has paid. For external refunds, supply the actual Paystack refund ID after processing it in Paystack." datasets={[
 {label:'Payments',resource:'payments',columns:['reference','customer_id','purpose','method','amount_kobo','status','created_at']},
 {label:'Wallet ledger',resource:'wallet-transactions',columns:['customer_id','kind','reference','amount_kobo','balance_after_kobo','created_at']},
 {label:'Withdrawals',resource:'withdrawals',columns:['reference','kind','entity_id','amount_kobo','status','account_name','bank_code','last_four','review_note','created_at'],actions:[{label:'Review withdrawal',path:r=>`/v1/admin/withdrawals/${rowId(r)}/review`,fields:reviewFields,show:r=>r.status==='requested',danger:true}]},
 {label:'Refunds',resource:'refunds',columns:['id','code','payment_method','amount_kobo','status','provider_refund_id','created_at'],actions:[{label:'Reconcile provider refund',path:r=>`/v1/admin/refunds/${rowId(r)}/reconcile`,fields:[field('provider_refund_id','Paystack refund ID')],show:r=>r.payment_method!=='wallet'&&r.status==='pending'}]},
 {label:'Finance policies',resource:'finance-policies',columns:['id','city_id','enabled','config','created_at']}
 ]}/>;}
const matchingFields=[
 field('initial_radius_m','First search distance (metres)','number',{min:100,max:50000,hint:'How far from the pickup to look for a rider first. e.g. 2000'}),
 field('max_radius_m','Furthest search distance (metres)','number',{min:100,max:100000,hint:'The search never goes wider than this. e.g. 8000'}),
 field('radius_step_m','Widen by (metres)','number',{min:100,max:50000,hint:'Added to the distance each time the search widens. e.g. 1000'}),
 field('expansion_seconds','Widen every (seconds)','number',{min:5,max:600,hint:'e.g. 30'}),
 field('offer_seconds','Time a rider has to accept (seconds)','number',{min:5,max:120,hint:'e.g. 30'}),
 field('search_seconds','Give up after (seconds)','number',{min:30,max:3600,hint:'When no rider is found. e.g. 300'}),
 field('location_max_age_seconds','Oldest rider location allowed (seconds)','number',{min:15,max:300,hint:'Riders with older positions are skipped. e.g. 120'}),
 field('max_accuracy_m','Least GPS accuracy allowed (metres)','number',{min:5,max:500,hint:'e.g. 100'})];
const financeFields=[field('enabled','Enable settlements','boolean'),field('vendor_commission_bps','Vendor commission (basis points)','number',{min:0,max:10000,hint:'Vendo’s share of food sales. 100 = 1%, so 1500 = 15%'}),field('rider_delivery_bps','Rider share of delivery fee (basis points)','number',{min:0,max:10000,hint:'100 = 1%, so 8000 = 80%'}),money('rider_fixed_kobo','Fixed rider earning'),field('settlement_hold_hours','Settlement hold hours','number',{min:1,max:720}),money('minimum_withdrawal_kobo','Minimum withdrawal')];
export function CitiesPage(){return <Workbench datasets={[{label:'Cities',path:'/v1/admin/cities',columns:['id','name','is_active','base_fare_kobo','per_km_rate_kobo','minimum_delivery_fee_kobo','minimum_food_subtotal_kobo','surge_bps','opens_at','closes_at'],actions:[
 {label:'Edit pricing',path:r=>`/v1/admin/cities/${rowId(r)}/pricing`,method:'PUT',fields:[field('is_active','Active service city','boolean'),money('base_fare_kobo','Base fare'),money('per_km_rate_kobo','Per kilometre'),money('minimum_delivery_fee_kobo','Minimum delivery'),money('minimum_food_subtotal_kobo','Minimum food subtotal'),field('surge_bps','Surge (basis points)','number',{min:10000,max:50000,hint:'10000 = normal price, 13000 = 1.3×'}),field('opens_at','Opens (HH:MM:SS, blank for unrestricted)','text',{nullable:true}),field('closes_at','Closes (HH:MM:SS)','text',{nullable:true})]},
 {label:'Set service boundary',path:r=>`/v1/admin/cities/${rowId(r)}/service-area`,method:'PUT',fields:[field('polygon','Boundary JSON array of {lat,lng} points','json')]},
 {label:'Create finance policy',path:r=>`/v1/admin/cities/${rowId(r)}/finance-policies`,fields:financeFields,danger:true,detail:'These terms apply to future orders. Enter the agreed business rates; no rates are preselected.'},
 {label:'Set matching policy',path:r=>`/v1/admin/cities/${rowId(r)}/matching-policy`,method:'PUT',detail:'How riders are found for an order. Without this, riders in the city cannot go online.',fields:matchingFields}
 ]}]}/>;}
const bannerFields=[field('title','Title'),field('body','Body','text',{optional:true}),field('city_id','City ID (blank = all cities)','text',{nullable:true}),field('image_url','HTTPS banner image URL','text',{nullable:true}),field('action','Tap action','select',{options:['food','dispatch','wallet','vendor']}),field('vendor_id','Vendor ID (required for vendor action)','text',{nullable:true}),field('starts_at','Starts','datetime-local'),field('ends_at','Ends','datetime-local'),field('active','Active','boolean'),field('priority','Priority','number',{min:0,max:100})];
const promoFields=[field('code','Promo code'),field('active','Active','boolean'),field('starts_at','Starts','datetime-local'),field('ends_at','Ends','datetime-local'),field('scope','Scope','select',{options:['all','food','dispatch']}),field('city_id','City ID (blank = all)','text',{nullable:true}),field('vendor_id','Vendor ID (optional)','text',{nullable:true}),field('basis','Discount basis','select',{options:['delivery','food_subtotal']}),field('kind','Discount kind','select',{options:['fixed','percent']}),field('value','Value (kobo for fixed; basis points for percent)','number',{min:1}),money('max_discount_kobo','Maximum discount'),money('minimum_total_kobo','Minimum order total'),field('max_uses','Total redemption limit','number',{min:1}),field('per_customer_limit','Per customer limit','number',{min:1})];
const referralFields=[field('enabled','Enabled','boolean'),money('referrer_reward_kobo','Referrer wallet reward'),money('referee_reward_kobo','New customer wallet reward'),money('minimum_order_kobo','Qualifying minimum order'),field('hold_days','Hold days','number',{min:1,max:90}),field('expiry_days','Expiry days','number',{min:1,max:365}),field('referrer_cap','Referrer reward count limit','number',{min:1,max:1000})];
export function PromotionsPage(){return <Workbench description="Referral rewards are wallet credits after qualification and the hold period. Percent promo values use basis points (1000 = 10%)." datasets={[
 {label:'Banners',resource:'banners',columns:['title','city_id','action','image_url','active','starts_at','ends_at'],create:{label:'Create banner',path:'/v1/admin/banners',fields:bannerFields},actions:[{label:'Edit banner',path:r=>`/v1/admin/banners/${rowId(r)}`,method:'PUT',fields:bannerFields}]},
 {label:'Promo codes',path:'/v1/admin/promos',columns:['code','active','kind','basis','value','max_discount_kobo','used_count','max_uses','starts_at','ends_at'],create:{label:'Create promo',path:'/v1/admin/promos',fields:promoFields},actions:[{label:'Edit promo',path:r=>`/v1/admin/promos/${rowId(r)}`,method:'PUT',fields:promoFields}]},
 {label:'Referral policies',resource:'referral-policies',columns:['enabled','config','created_at'],create:{label:'Set referral policy',path:'/v1/admin/referrals/policy',method:'PUT',fields:referralFields},actions:[{label:'Use as new policy',path:'/v1/admin/referrals/policy',method:'PUT',fields:referralFields,initial:r=>({...r.config as Row,enabled:r.enabled})}]}
 ]}/>;}
export function NotificationsPage(){return <Workbench description="Campaigns queue push messages through the notification worker. Recipients are active accounts in the selected cities with push enabled and registered devices. Device sends are provider acknowledgements; inbox reads are not push-open tracking." datasets={[{label:'Push campaigns',path:'/v1/admin/broadcasts',columns:['title','body','audience','city_ids','send_at','status','recipients','device_sends','inbox_reads'],create:{label:'Create campaign',path:'/v1/admin/broadcasts',fields:[field('audience','Audience','select',{options:['customers','riders','vendors']}),field('city_ids','Service cities (select one or more)','cities'),field('title','Title'),field('body','Message'),field('send_at','Send at (blank = now)','datetime-local',{optional:true})],detail:'Queue now or schedule up to 90 days ahead. Recipients are evaluated at send time.',danger:true},actions:[{label:'Cancel campaign',path:r=>`/v1/admin/broadcasts/${rowId(r)}/cancel`,show:r=>r.status==='scheduled',danger:true}]}]}/>;}
export function AuditPage(){return <Workbench datasets={[{label:'Audit log',resource:'audits',columns:['created_at','actor_name','actor_id','action','target_id','reason']}]}/>;}
export function SupportPage(){return <Workbench datasets={[{label:'Support tickets',path:'/v1/admin/support/tickets',columns:['id','subject','category','order_id','status','created_at'],actions:[{label:'Reply to ticket',path:r=>`/v1/admin/support/tickets/${rowId(r)}/messages`,fields:[field('message','Reply')]},{label:'Resolve ticket',path:r=>`/v1/admin/support/tickets/${rowId(r)}/resolve`,show:r=>r.status==='open'}]}]} detail={r=><TicketMessages id={rowId(r)}/>}/>;}
function TicketMessages({id}:{id:string}){const q=useQuery({queryKey:['ticket',id],queryFn:()=>request<{messages:Row[]}>(`/v1/admin/support/tickets/${id}`)});return q.isError?<p className="text-danger">{q.error.message}</p>:!q.data?<Spinner/>:<section>{q.data.messages.map((m,i)=><p key={i}><strong>{m.from_support?'Support':'Customer'}:</strong> {String(m.message)}</p>)}</section>;}
export { OverviewPage } from './OverviewPage';
export { AnalyticsPage } from './AnalyticsPage';
