"use client";
import {useState,useRef,type ReactNode} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,request} from '@/api/client';
import type {Row} from '@/api/types';
import {useCities} from '@/api/queries';
import {downloadCsv,toCsv} from '@/lib/csv';
import {Button,Input,Modal,Spinner} from './ui';

export type Field={key:string;label:string;type?:'text'|'number'|'boolean'|'select'|'json'|'cities'|'datetime-local';options?:string[];nullable?:boolean;optional?:boolean;min?:number;max?:number;value?:unknown};
export type Action={label:string;path:string|((row:Row)=>string);method?:string;fields?:Field[];initial?:(row:Row)=>Row;transform?:(value:Row,row:Row)=>Row;show?:(row:Row)=>boolean;detail?:string;danger?:boolean};
export type Dataset={label:string;resource?:string;path?:string;columns:string[];actions?:Action[];create?:Action;id?:string};
export const text=(v:unknown):string=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
export const rowId=(r:Row)=>String(r.id??r.profile_id);
export const field=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label,type,...extra});
export const reason=field('reason','Reason (at least 10 characters)');
export const note=field('note','Review note (at least 10 characters)');
export const money=(key:string,label:string)=>field(key,label+' (kobo)', 'number',{min:0});
export function EditForm({action,row={},onClose}:{action:Action;row?:Row;onClose:()=>void}){
 const initial=action.initial?.(row)??row;const [values,setValues]=useState<Row>(()=>Object.fromEntries((action.fields??[]).map(f=>[f.key,f.type==='datetime-local'&&initial[f.key]?new Date(Date.parse(String(initial[f.key]))-new Date(String(initial[f.key])).getTimezoneOffset()*60000).toISOString().slice(0,16):initial[f.key]??f.value??(f.type==='boolean'?false:'')])));
 const reach=useQuery({queryKey:['campaign-reach',values.audience,values.city_ids],queryFn:()=>request<{recipients:number}>('/v1/admin/broadcasts/count','POST',{audience:values.audience,city_ids:values.city_ids}),enabled:action.path==='/v1/admin/broadcasts'&&!!values.audience&&Array.isArray(values.city_ids)&&values.city_ids.length>0});
 const cities=useCities();const keys=useRef(new Map<string,string>());const client=useQueryClient();
 const save=useMutation({mutationFn:async()=>{
  const body:Row={};for(const f of action.fields??[]){const value=values[f.key];if((value===''||value==null)&&(f.optional||f.nullable)){if(f.nullable)body[f.key]=null;continue;}
   body[f.key]=f.type==='number'?Number(value):f.type==='json'?(typeof value==='object'?value:JSON.parse(String(value))):f.type==='datetime-local'?new Date(String(value)).toISOString():value;}
  const payload=action.transform?.(body,row)??body;const path=typeof action.path==='function'?action.path(row):action.path;const fingerprint=JSON.stringify({path,payload});let key=keys.current.get(fingerprint);if(!key){key=crypto.randomUUID();keys.current.set(fingerprint,key);}
  const result=await request(path,action.method??'POST',payload,true,key);keys.current.delete(fingerprint);return result;
 },onSuccess:()=>{client.invalidateQueries();onClose();}});
 return <Modal title={action.label} wide onClose={onClose}><form className="stack" onSubmit={e=>{e.preventDefault();if(action.danger&&!window.confirm(`Confirm: ${action.label}?`))return;save.mutate();}}>
 {action.detail?<p className="muted">{action.detail}</p>:null}<div className="form-grid">{(action.fields??[]).map(f=>f.type==='cities'?<label key={f.key} className="field"><span>{f.label}</span><select className="select" multiple required value={Array.isArray(values[f.key])?values[f.key] as string[]:[]} onChange={e=>setValues(v=>({...v,[f.key]:Array.from(e.target.selectedOptions,o=>o.value)}))}>{cities.data?.filter(c=>c.is_active).map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name)}</option>)}</select>{cities.isError?<span className="field__error">{cities.error.message}</span>:null}</label>:f.key==='city_id'?<label key={f.key} className="field"><span>{f.label.replace(' ID','')}</span><select className="select" required={!f.nullable&&!f.optional} value={String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}><option value="">{f.nullable?'All cities':'Select a city…'}</option>{cities.data?.map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.name)}</option>)}</select></label>:f.type==='boolean'?<label key={f.key} className="field"><span>{f.label}</span><input type="checkbox" checked={!!values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.checked}))}/></label>:f.type==='select'?<label key={f.key} className="field"><span>{f.label}</span><select className="select" required={!f.optional&&!f.nullable} value={String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}><option value="">Select…</option>{f.options?.map(v=><option key={v} value={v}>{v}</option>)}</select></label>:f.type==='json'?<label key={f.key} className="field"><span>{f.label}</span><textarea className="textarea" rows={4} required={!f.optional&&!f.nullable} value={typeof values[f.key]==='object'?JSON.stringify(values[f.key],null,2):String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/></label>:<Input key={f.key} label={f.label} type={f.type??'text'} required={!f.optional&&!f.nullable} min={f.min} max={f.max} step={f.type==='number'?'any':undefined} value={f.type==='datetime-local'&&values[f.key]?String(values[f.key]).slice(0,16):String(values[f.key]??'')} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>)}</div>
 {action.path==='/v1/admin/broadcasts'?<p className="muted">{reach.isError?reach.error.message:reach.data?`Current eligible audience: ${reach.data.recipients} accounts. The worker checks recipients again at send time.`:reach.isFetching?'Counting eligible recipients…':'Choose an audience and cities to preview reach.'}</p>:null}
 {save.isError?<p role="alert" className="text-danger">{save.error.message}</p>:null}<div className="row"><Button type="submit" loading={save.isPending} variant={action.danger?'danger':'primary'}>Confirm {action.label.toLowerCase()}</Button><Button variant="secondary" onClick={onClose}>Cancel</Button></div></form></Modal>;
}
export function Workbench({datasets,description,detail}:{datasets:Dataset[];description?:string;detail?:(row:Row,tab:Dataset)=>ReactNode}){
 const [tabIndex,setTabIndex]=useState(0);const [offset,setOffset]=useState(0);const [search,setSearch]=useState('');const [selected,setSelected]=useState<Row|null>(null);const [editing,setEditing]=useState<{action:Action;row:Row}|null>(null);const tab=datasets[tabIndex];
 const data=useQuery({queryKey:['admin-data',tab.resource??tab.path,tab.id,offset],queryFn:async()=>tab.resource?(await api.data(tab.resource,offset,tab.id)).items:api.list(tab.path!,offset),refetchInterval:15000});
 const rows=(data.data??[]).filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
 return <div className="stack">{description?<p className="muted">{description}</p>:null}<div className="wrap">{datasets.map((d,i)=><Button key={d.label} variant={i===tabIndex?'primary':'secondary'} size="sm" onClick={()=>{setTabIndex(i);setOffset(0);setSelected(null);}}>{d.label}</Button>)}</div>
 <div className="toolbar"><Input label="Search this page" value={search} onChange={e=>setSearch(e.target.value)}/><span className="grow"/><Button variant="secondary" onClick={()=>data.refetch()}>Refresh</Button><Button variant="secondary" disabled={!rows.length} onClick={()=>downloadCsv(`vendo-${tab.label.toLowerCase().replaceAll(' ','-')}.csv`,toCsv(tab.columns,rows.map(r=>tab.columns.map(k=>text(r[k])))))}>Export this page</Button>{tab.create?<Button onClick={()=>setEditing({action:tab.create!,row:{}})}>{tab.create.label}</Button>:null}</div>
 {data.isError?<div className="card"><p role="alert" className="text-danger">{data.error.message}</p><Button onClick={()=>data.refetch()}>Retry</Button></div>:!data.data?<Spinner/>:<section className="card card--flush"><div className="table-wrap"><table className="table"><thead><tr>{tab.columns.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={rowId(r)==='undefined'?i:rowId(r)}>{tab.columns.map(k=><td key={k} style={{maxWidth:260,overflowWrap:'anywhere'}}>{text(r[k])}</td>)}<td><div className="wrap"><Button variant="ghost" size="sm" onClick={()=>setSelected(r)}>Details</Button>{tab.actions?.filter(a=>!a.show||a.show(r)).map(a=><Button key={a.label} variant={a.danger?'danger':'secondary'} size="sm" onClick={()=>setEditing({action:a,row:r})}>{a.label}</Button>)}</div></td></tr>)}</tbody></table>{!rows.length?<p style={{padding:20}}>No records match.</p>:null}</div></section>}
 <div className="between"><Button variant="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</Button><span className="small muted">Records {offset+1}–{offset+(data.data?.length??0)}</span><Button variant="secondary" disabled={(data.data?.length??0)<50||offset>=10000} onClick={()=>setOffset(offset+50)}>Next</Button></div>
 {selected?<Modal title={`${tab.label} details`} wide onClose={()=>setSelected(null)}><div className="stack">{detail?.(selected,tab)}<dl>{Object.entries(selected).map(([k,v])=><div className="stack-sm" key={k} style={{paddingBottom:12}}><dt className="label">{k.replaceAll('_',' ')}</dt><dd style={{margin:0,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{typeof v==='object'&&v!==null?JSON.stringify(v,null,2):text(v)}</dd></div>)}</dl></div></Modal>:null}
 {editing?<EditForm action={editing.action} row={editing.row} onClose={()=>setEditing(null)}/>:null}</div>;
}
