import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresAddressRepository } from '../src/modules/addresses/repository.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { fixtures, alice, bob } from './helpers.js';
import type { Point } from '../src/lib/geo.js';

test('Addresses and maps API/SQL: ownership, partial edits/defaults, city preference, polygon checks, lookup filtering and routing', async (t) => {
  const db = new PGlite(); t.after(() => db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users (id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  for (const file of ['202610030001_accounts.sql', '202610030002_account_controls.sql', '202610030003_food_court.sql', '202610030004_dispatch.sql', '202610030005_addresses_maps.sql', '202610030006_orders.sql', '202610030007_payments_wallet.sql', '202610030008_matching_tracking.sql', '202610030009_notifications_extras.sql', '202610030010_operations_finance_chat.sql','202610030011_media_storage.sql','202610030012_vendor_registration.sql']) await db.exec(await readFile(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8'));
  const query = (sql: string, values?: unknown[]) => db.query(sql, values);
  const pool = { query, connect: async () => ({ query, release() {} }) } as unknown as pg.Pool;
  const profiles = new PostgresProfileRepository(pool), addresses = new PostgresAddressRepository(pool);
  const admin = { id: randomUUID(), phone: '+2348011111111' };
  for (const user of [alice, bob, admin]) { await db.query('INSERT INTO auth.users (id) VALUES ($1)', [user.id]); await profiles.bootstrap(user.id, user.phone); }
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [admin.id]);
  const cityId = (await db.query<{ id: string }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
  const otherId = (await db.query<{ id: string }>("SELECT id FROM public.cities WHERE name='Kano'")).rows[0]!.id;
  await db.query('UPDATE public.cities SET is_active=true WHERE id=$1', [cityId]);
  const polygon = [{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }];
  const fixture = fixtures(), authenticate = fixture.dependencies.auth.authenticate;
  fixture.dependencies.auth.authenticate = async (token) => token === 'admin' ? admin : authenticate(token);
  const searchCalls: { bbox: number[]; bias: Point }[] = [];
  const candidates = [
    { id: 'osm:N:1', name: 'Kawo Road', address: 'Kawo Road, Kaduna', location: { lat: 10.5, lng: 7.5 } },
    { id: 'osm:N:2', name: 'Outside', address: 'Outside Kaduna', location: { lat: 12, lng: 7.5 } },
  ];
  fixture.dependencies.geocoder = { async search(input) { searchCalls.push(input); return candidates; }, async reverse() { return candidates; } };
  let routingCalls = 0;
  fixture.dependencies.routing.route = async () => { routingCalls++; return { distance_m: 1500, duration_s: 300, geometry: { type: 'LineString', coordinates: [[7.5,10.5],[7.6,10.6]] } }; };
  const app = await buildApp(readEnv({ NODE_ENV: 'test' }), { ...fixture.dependencies, profiles, addresses }); t.after(() => app.close());
  const headers = (user = 'alice') => ({ authorization: `Bearer ${user}` });
  assert.equal((await app.inject('/v1/cities')).json().items.length, 1);
  assert.equal((await app.inject(`/v1/cities/${otherId}`)).statusCode, 404);
  const check = (payload: Record<string, unknown>) => app.inject({ method: 'POST', url: '/v1/maps/service-area', payload });
  assert.equal((await check({ lat: 10.5, lng: 7.5, city_id: cityId })).json().reason, 'service_area_not_configured');
  const boundary = (poly = polygon, user = 'admin') => app.inject({ method: 'PUT', url: `/v1/admin/cities/${cityId}/service-area`, headers: headers(user), payload: { polygon: poly } });
  assert.equal((await boundary(polygon, 'alice')).statusCode, 403);
  assert.equal((await boundary([polygon[0]!, polygon[2]!, polygon[1]!, polygon[3]!])).statusCode, 400);
  assert.equal((await boundary()).statusCode, 200);
  assert.equal((await check({ lat: 10.5, lng: 7.5 })).json().city.id, cityId);
  assert.equal((await check({ lat: 10, lng: 7.5 })).json().serviceable, true);
  assert.equal((await check({ lat: 12, lng: 7.5 })).json().reason, 'outside_service_area');
  assert.equal((await check({ lat: 100, lng: 7.5 })).statusCode, 400);
  await db.query('UPDATE public.cities SET is_active=true,service_polygon=$2 WHERE id=$1', [otherId, JSON.stringify(polygon)]);
  assert.equal((await check({ lat: 10.5, lng: 7.5 })).statusCode, 409);
  assert.equal((await check({ lat: 10.5, lng: 7.5, city_id: cityId })).json().serviceable, true);
  await db.query('UPDATE public.cities SET is_active=false WHERE id=$1', [otherId]);
  const input = { city_id: cityId, label: 'Home', address: 'Kawo Road', location: { lat: 10.5, lng: 7.5 }, landmark: 'Blue gate', note: 'Call first', is_default: true };
  const create = (payload: Record<string, unknown> = input) => app.inject({ method: 'POST', url: '/v1/me/addresses', headers: headers(), payload });
  assert.equal((await app.inject('/v1/me/addresses')).statusCode, 401);
  assert.equal((await create({ ...input, profile_id: bob.id })).statusCode, 400);
  assert.equal((await create({ ...input, location: { lat: 12, lng: 7.5 } })).statusCode, 400);
  const first = await create(); assert.equal(first.statusCode, 201, first.body);
  const id = first.json().id;
  assert.equal(first.json().profile_id, undefined); assert.equal(first.json().note, 'Call first');
  const patch = (payload: Record<string, unknown>, user = 'alice', addressId = id) => app.inject({ method: 'PATCH', url: `/v1/me/addresses/${addressId}`, headers: headers(user), payload });
  assert.equal((await patch({})).statusCode, 400);
  const renamed = await patch({ label: 'My home' }); assert.equal(renamed.statusCode, 200, renamed.body);
  assert.equal(renamed.json().landmark, 'Blue gate'); assert.equal(renamed.json().note, 'Call first'); assert.equal(renamed.json().is_default, true);
  assert.equal((await patch({ label: 'Stolen' }, 'bob')).statusCode, 404);
  assert.equal((await app.inject({ url: `/v1/me/addresses/${id}`, headers: headers('bob') })).statusCode, 404);
  assert.equal((await app.inject({ method: 'DELETE', url: `/v1/me/addresses/${id}`, headers: headers('bob') })).statusCode, 404);
  const second = await create({ ...input, label: 'Work' }); assert.equal(second.statusCode, 201, second.body);
  const listed = (await app.inject({ url: '/v1/me/addresses', headers: headers() })).json().items;
  assert.equal(listed.length, 2); assert.equal(listed.filter((item: { is_default: boolean }) => item.is_default).length, 1);
  assert.equal(listed[0].id, second.json().id);
  // Legacy addresses without a city remain readable and can be upgraded by selecting one.
  const legacy = (await db.query<{ id: string }>("INSERT INTO public.saved_addresses (profile_id,label,address,latitude,longitude) VALUES ($1,'Legacy','Old address',10.5,7.5) RETURNING id", [alice.id])).rows[0]!.id;
  assert.equal((await app.inject({ url: `/v1/me/addresses/${legacy}`, headers: headers() })).json().city_id, null);
  assert.equal((await patch({ label: 'Updated legacy' }, 'alice', legacy)).statusCode, 400);
  assert.equal((await patch({ city_id: cityId }, 'alice', legacy)).statusCode, 200);
  const chooseCity = (city_id: string | null) => app.inject({ method: 'PATCH', url: '/v1/me/city', headers: headers(), payload: { city_id } });
  assert.equal((await chooseCity(otherId)).statusCode, 409);
  assert.equal((await chooseCity(cityId)).json().city_id, cityId);
  assert.equal((await app.inject({ url: '/v1/me/city', headers: headers() })).json().city.id, cityId);
  assert.equal((await chooseCity(null)).json().city, null);
  assert.equal((await app.inject(`/v1/maps/search?city_id=${cityId}&q=Kawo`)).statusCode, 401);
  const search = await app.inject({ url: `/v1/maps/search?city_id=${cityId}&q=Kawo`, headers: headers() });
  assert.equal(search.statusCode, 200, search.body); assert.equal(search.json().items.length, 1); assert.equal(search.json().items[0].city_id, cityId);
  assert.deepEqual(searchCalls[0]!.bbox, [7, 10, 8, 11]); assert.deepEqual(searchCalls[0]!.bias, { lat: 10.5, lng: 7.5 });
  assert.equal((await app.inject({ url: `/v1/maps/search?city_id=${cityId}&q=Ka`, headers: headers() })).statusCode, 400);
  assert.equal((await app.inject({ url: `/v1/maps/search?city_id=${cityId}&q=Kawo&lat=12&lng=7.5`, headers: headers() })).statusCode, 400);
  const reverse = await app.inject({ url: `/v1/maps/reverse?city_id=${cityId}&lat=10.5&lng=7.5`, headers: headers() });
  assert.equal(reverse.json().items.length, 1);
  assert.equal((await app.inject({ url: `/v1/maps/reverse?city_id=${cityId}&lat=12&lng=7.5`, headers: headers() })).statusCode, 400);
  const route = (dropoff = { lat: 10.6, lng: 7.6 }) => app.inject({ method: 'POST', url: '/v1/maps/route', headers: headers(), payload: { city_id: cityId, pickup: input.location, dropoff } });
  assert.equal((await route({ lat: 12, lng: 7.5 })).statusCode, 400); assert.equal(routingCalls, 0);
  const road = await route();
  assert.equal(road.json().distance_m, 1500); assert.equal(road.json().geometry.type, 'LineString'); assert.equal(routingCalls, 1);
  await db.query("UPDATE public.cities SET opens_at='00:00:00',closes_at='00:00:01' WHERE id=$1", [cityId]);
  assert.equal((await check({ lat: 10.5, lng: 7.5, city_id: cityId })).json().reason, 'city_closed');
  assert.equal((await route()).statusCode, 409);
  assert.equal((await create({ ...input, is_default: false })).statusCode, 201); // Saving is independent of operating hours.
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [bob.id]); await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.saved_addresses')).rows.length, 0);
  await assert.rejects(() => db.query("UPDATE public.saved_addresses SET note='Changed'")); await db.exec('RESET ROLE');
  await db.query("UPDATE public.profiles SET status='suspended' WHERE id=$1", [alice.id]);
  assert.equal((await app.inject({ url: '/v1/me/addresses', headers: headers() })).statusCode, 403);
  assert.equal((await patch({ label: 'No' })).statusCode, 403);
  await db.query("UPDATE public.profiles SET status='active' WHERE id=$1", [alice.id]);
  assert.equal((await app.inject({ method: 'DELETE', url: `/v1/me/addresses/${id}`, headers: headers() })).statusCode, 200);
  assert.equal((await app.inject({ url: `/v1/me/addresses/${id}`, headers: headers() })).statusCode, 404);
});
