import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';

test('account migration, profile constraints, concurrent bootstrap and read-only RLS', async (t) => {
  const db = new PGlite();
  t.after(() => db.close());
  // Supabase-owned objects needed by our migration. This runs real Postgres SQL
  // through PGlite; hosted Supabase integration still needs staging credentials.
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth;
    CREATE TABLE auth.users (id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
      $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    GRANT USAGE ON SCHEMA public, auth TO anon, authenticated, service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated;`);
  await db.exec(await readFile(new URL('../supabase/migrations/202610030001_accounts.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030002_account_controls.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030003_food_court.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030004_dispatch.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030005_addresses_maps.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030006_orders.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030007_payments_wallet.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030008_matching_tracking.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030009_notifications_extras.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030010_operations_finance_chat.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030011_media_storage.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610030012_vendor_registration.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610060013_vendor_portal.sql', import.meta.url), 'utf8'));
  const repository = new PostgresProfileRepository({ query: (sql: string, values: unknown[]) => db.query(sql, values) } as unknown as pg.Pool);
  const id = randomUUID();
  const otherId = randomUUID();
  await db.query('INSERT INTO auth.users (id) VALUES ($1), ($2)', [id, otherId]);
  const [first, duplicate] = await Promise.all([repository.bootstrap(id, '+2348144461726'), repository.bootstrap(id, '+2348144461726')]);
  assert.equal(first.id, duplicate.id);
  assert.equal(first.onboarding_step, 'name_required');
  await assert.rejects(() => db.query('UPDATE public.profiles SET email = $1 WHERE id = $2', ['alice@example.com', id]));
  const named = await repository.setName(id, 'Alice Bello');
  assert.equal(named.onboarding_step, 'email_required');
  const complete = await repository.setEmail(id, 'alice@example.com');
  assert.equal(complete.onboarding_step, 'complete');
  assert.equal(complete.email_verified, false);
  await db.query('UPDATE public.profiles SET email_verified = true WHERE id = $1', [id]);
  assert.equal((await repository.setEmail(id, 'alice@example.com')).email_verified, true);
  assert.equal((await repository.setEmail(id, 'changed@example.com')).email_verified, false);
  assert.equal((await repository.bootstrap(id, '+2348144461726')).name, 'Alice Bello');
  await repository.bootstrap(otherId, '+2348140454988');
  await db.query(`INSERT INTO public.saved_addresses (profile_id, label, address, latitude, longitude)
    VALUES ($1, 'Home', 'Kawo Road', 10.5, 7.4), ($2, 'Home', 'Other Road', 10.6, 7.5)`, [id, otherId]);
  const count = await db.query<{ count: number }>('SELECT count(*)::int AS count FROM public.profiles');
  assert.equal(count.rows[0]?.count, 2);
  await db.query("SELECT set_config('request.jwt.claim.sub', $1, false)", [id]);
  await db.exec('SET ROLE authenticated');
  const visible = await db.query<{ id: string }>('SELECT id FROM public.profiles');
  assert.deepEqual(visible.rows, [{ id }]);
  const addresses = await db.query<{ profile_id: string }>('SELECT profile_id FROM public.saved_addresses');
  assert.deepEqual(addresses.rows, [{ profile_id: id }]);
  await assert.rejects(() => db.query("UPDATE public.profiles SET role = 'admin' WHERE id = $1", [id]));
  await assert.rejects(() => db.query('INSERT INTO public.profiles (id, phone) VALUES ($1, $2)', [randomUUID(), '+2348144461726']));
  await db.exec('RESET ROLE; SET ROLE anon');
  await assert.rejects(() => db.query('SELECT * FROM public.profiles'));
  const cities = await db.query('SELECT * FROM public.cities');
  assert.equal(cities.rows.length, 0);
  await db.exec('RESET ROLE');
  assert.equal((await db.query('SELECT * FROM public.cities')).rows.length, 4);
  const query = (sql: string, values?: unknown[]) => db.query(sql, values);
  const accounts = new PostgresAccountRepository({ query, connect: async () => ({ query, release() {} }) } as unknown as pg.Pool);
  const challengeId = randomUUID();
  const hash = 'a'.repeat(64);
  assert.equal(await accounts.issueVerification(id, { id: challengeId, email: 'changed@example.com', hash, expiresAt: new Date(Date.now() + 600000) }), true);
  assert.equal(await accounts.verifyEmail(otherId, challengeId, hash), null);
  assert.equal(await accounts.verifyEmail(id, challengeId, 'b'.repeat(64)), null);
  const attempts = await db.query<{ attempts: number }>('SELECT attempts FROM vendo_internal.email_verifications WHERE profile_id = $1', [id]);
  assert.equal(attempts.rows[0]?.attempts, 1);
  assert.equal((await accounts.verifyEmail(id, challengeId, hash))?.email_verified, true);
  assert.equal(await accounts.verifyEmail(id, challengeId, hash), null);
  await repository.setEmail(id, 'new@example.com');
  assert.equal((await db.query('SELECT * FROM vendo_internal.email_verifications WHERE profile_id = $1', [id])).rows.length, 0);
  const expiredId = randomUUID();
  await accounts.issueVerification(id, { id: expiredId, email: 'new@example.com', hash, expiresAt: new Date(0) });
  assert.equal(await accounts.verifyEmail(id, expiredId, hash), null);
  const lockedId = randomUUID();
  await accounts.issueVerification(id, { id: lockedId, email: 'new@example.com', hash, expiresAt: new Date(Date.now() + 600000) });
  for (let attempt = 0; attempt < 5; attempt++) assert.equal(await accounts.verifyEmail(id, lockedId, 'b'.repeat(64)), null);
  assert.equal(await accounts.verifyEmail(id, lockedId, hash), null);
  assert.equal((await accounts.getPreferences(id)).theme, 'system');
  assert.equal((await accounts.updatePreferences(id, { theme: 'dark', email_enabled: false })).email_enabled, false);
  assert.equal((await accounts.getPreferences(id)).theme, 'dark');
  await accounts.requestRecovery('+2348144461726', 'contact@example.com', 'I cannot access my phone any longer.');
  await db.exec('SET ROLE authenticated');
  await assert.rejects(() => db.query('SELECT * FROM vendo_internal.email_verifications'));
  await assert.rejects(() => db.query('SELECT * FROM vendo_internal.account_recovery_requests'));
  await assert.rejects(() => db.query("UPDATE public.account_preferences SET theme = 'light'"));
  await db.exec('RESET ROLE');
  const deletionId = await accounts.requestDeletion(id, 'No longer using the app');
  assert.ok(deletionId);
  assert.equal((await repository.bootstrap(id, '+2348144461726')).status, 'deactivated');
  await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.profiles')).rows.length, 0);
  assert.equal((await db.query('SELECT * FROM public.saved_addresses')).rows.length, 0);
  assert.equal((await db.query('SELECT * FROM public.account_preferences')).rows.length, 0);
  await db.exec('RESET ROLE');
});

test('email identity onboards name then contact phone and preserves phone on reload', async (t) => {
  const db = new PGlite(); t.after(() => db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role; CREATE SCHEMA auth;
    CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT NULL::uuid $$;`);
  await db.exec(await readFile(new URL('../supabase/migrations/202610030001_accounts.sql', import.meta.url), 'utf8'));
  await db.exec(await readFile(new URL('../supabase/migrations/202610060014_email_auth.sql', import.meta.url), 'utf8'));
  const repo = new PostgresProfileRepository({ query: (sql: string, values: unknown[]) => db.query(sql, values) } as unknown as pg.Pool);
  const id = randomUUID(); await db.query('INSERT INTO auth.users(id) VALUES($1)', [id]);
  const initial = await repo.bootstrap(id, '', 'owner@example.com');
  assert.equal(initial.email_verified, true); assert.equal(initial.phone, null); assert.equal(initial.onboarding_step, 'name_required');
  assert.equal((await repo.setName(id, 'Store Owner')).onboarding_step, 'phone_required');
  assert.equal((await repo.setPhone(id, '+2348030000000')).onboarding_step, 'complete');
  assert.equal((await repo.bootstrap(id, '', 'owner@example.com')).phone, '+2348030000000');
});
