import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { ApiError } from '../src/lib/errors.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { DeliveryCodes } from '../src/modules/dispatch/codes.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { fixtures, alice, bob } from './helpers.js';

const secret = 'test-dispatch-secret-with-at-least-32-characters';
test('delivery codes are four digits, encrypted, and bound to order and secret', () => {
  const codes = new DeliveryCodes(secret), id = randomUUID();
  const generated = codes.generate(id);
  const code = codes.decrypt(id, generated.encrypted);
  assert.match(code, /^\d{4}$/);
  assert.equal(codes.hash(id, code), generated.hash);
  assert.notEqual(codes.hash(randomUUID(), code), generated.hash);
  assert.throws(() => codes.decrypt(randomUUID(), generated.encrypted), /temporarily unavailable/);
  assert.throws(() => new DeliveryCodes('another-secret-with-at-least-32-characters').decrypt(id, generated.encrypted), /temporarily unavailable/);
  assert.throws(() => new DeliveryCodes().generate(id), /not configured/);
  assert.throws(() => readEnv({ DISPATCH_DELIVERY_CODE_SECRET: 'short' }), /Invalid configuration/);
});

test('Dispatch API and SQL: same-city quotes, package limits, unpaid checkout, private codes, handover lockout and send-again', async (t) => {
  const db = new PGlite(); t.after(() => db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users (id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  for (const file of ['202610030001_accounts.sql', '202610030002_account_controls.sql', '202610030003_food_court.sql', '202610030004_dispatch.sql', '202610030005_addresses_maps.sql', '202610030006_orders.sql', '202610030007_payments_wallet.sql', '202610030008_matching_tracking.sql', '202610030009_notifications_extras.sql', '202610030010_operations_finance_chat.sql','202610030011_media_storage.sql','202610030012_vendor_registration.sql','202610060013_vendor_portal.sql']) {
    await db.exec(await readFile(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8'));
  }
  const query = (sql: string, values?: unknown[]) => db.query(sql, values);
  const pool = { query, connect: async () => ({ query, release() {} }) } as unknown as pg.Pool;
  const profiles = new PostgresProfileRepository(pool), dispatch = new PostgresDispatchRepository(pool);
  const accounts = new PostgresAccountRepository(pool);
  const admin = { id: randomUUID(), phone: '+2348011111111' }, rider = { id: randomUUID(), phone: '+2348022222222' }, otherRider = { id: randomUUID(), phone: '+2348033333333' };
  for (const identity of [alice, bob, admin, rider, otherRider]) {
    await db.query('INSERT INTO auth.users (id) VALUES ($1)', [identity.id]);
    await profiles.bootstrap(identity.id, identity.phone);
    await profiles.setName(identity.id, 'Test User'); await profiles.setEmail(identity.id, `${identity.id}@example.com`);
  }
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [admin.id]);
  await db.query("UPDATE public.profiles SET role='rider' WHERE id=ANY($1::uuid[])", [[rider.id, otherRider.id]]);
  const cityId = (await db.query<{ id: string }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
  const polygon = [{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }];
  await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1', [cityId, JSON.stringify(polygon)]);
  const fixture = fixtures(), originalAuth = fixture.dependencies.auth.authenticate;
  fixture.dependencies.auth.authenticate = async (token) => token === 'admin' ? admin : token === 'rider' ? rider : token === 'other-rider' ? otherRider : originalAuth(token);
  fixture.dependencies.routing.route = async () => ({ distance_m: 1501, duration_s: 301 });
  const dependencies = { ...fixture.dependencies, profiles, accounts, dispatch, food: new PostgresFoodRepository(pool) };
  const app = await buildApp(readEnv({ NODE_ENV: 'test', DISPATCH_DELIVERY_CODE_SECRET: secret }), dependencies);
  t.after(() => app.close());
  const auth = (user = 'alice') => ({ authorization: `Bearer ${user}` });
  const config = { size: 'small', label: 'Small parcel', fee_kobo: 10001, max_weight_g: 5000, max_length_cm: 40, max_width_cm: 30, max_height_cm: 30, is_active: true };
  const configure = (payload = config, user = 'admin') => app.inject({ method: 'PUT', url: `/v1/admin/cities/${cityId}/dispatch-packages`, headers: auth(user), payload });
  assert.equal((await configure(config, 'alice')).statusCode, 403);
  const configured = await configure();
  assert.equal(configured.statusCode, 200, configured.body);
  const packageList = await app.inject(`/v1/dispatch/packages?city_id=${cityId}`);
  assert.equal(packageList.json().items[0].max_weight_g, 5000);
  const input = { type: 'dispatch', city_id: cityId, pickup: { lat: 10.5, lng: 7.5, address: 'Pickup', landmark: 'Blue gate', note: 'Call me' }, dropoff: { lat: 10.6, lng: 7.6, address: 'Drop-off' }, package: { size: 'small', description: 'Shoes', fragile: true, fits_size: true, prohibited_items_acknowledged: true, weight_g: 1000 }, receiver: { name: 'Receiver Name', phone: '0814 045 4988' } };
  const requestQuote = (payload: Record<string, unknown> = input, user = 'alice') => app.inject({ method: 'POST', url: '/v1/orders/quote', headers: auth(user), payload });
  assert.equal((await requestQuote({ ...input, package: { ...input.package, prohibited_items_acknowledged: false } })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, package: { ...input.package, weight_g: 5001 } })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, package: { ...input.package, dimensions_cm: { length: 41, width: 20, height: 20 } } })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, dropoff: { lat: 12, lng: 7.6, address: 'Other city' } })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, dropoff: input.pickup })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, receiver: { name: 'Receiver', phone: '1234' } })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, scheduled_at: '2026-10-04T12:00:00Z' })).statusCode, 400);
  assert.equal((await requestQuote({ ...input, package: { ...input.package, size: 'large' } })).statusCode, 503);
  await db.query('UPDATE public.profiles SET email=NULL WHERE id=$1', [bob.id]);
  assert.equal((await requestQuote(input, 'bob')).statusCode, 403);
  await profiles.setEmail(bob.id, 'bob@example.com');
  const quote = async () => { const response = await requestQuote(); assert.equal(response.statusCode, 200, response.body); return response.json(); };
  const originalRoute = fixture.dependencies.routing.route;
  fixture.dependencies.routing.route = async () => { throw new ApiError(503, 'ROUTING_UNAVAILABLE', 'Routing unavailable'); };
  assert.equal((await requestQuote()).statusCode, 503);
  fixture.dependencies.routing.route = originalRoute;
  const first = await quote();
  assert.equal(first.total_kobo, 56000); assert.equal(first.distance_fee_kobo, 15010); assert.equal(first.rounding_kobo, 989);
  assert.equal(first.receiver.phone, bob.phone); assert.equal(first.eta_minutes, 6);
  const checkout = (id: string, key: string, user = 'alice', type = 'dispatch') => app.inject({ method: 'POST', url: '/v1/orders', headers: { ...auth(user), 'idempotency-key': key }, payload: { type, quote_id: id, payment_method: 'card' } });
  assert.equal((await checkout(first.id, 'foreign_key', 'bob')).statusCode, 409);
  const noSecret = await buildApp(readEnv({ NODE_ENV: 'test' }), dependencies);
  const unavailable = await noSecret.inject({ method: 'POST', url: '/v1/orders', headers: { ...auth(), 'idempotency-key': 'missing_secret' }, payload: { type: 'dispatch', quote_id: first.id, payment_method: 'card' } });
  assert.equal(unavailable.statusCode, 503, unavailable.body);
  await noSecret.close();
  assert.equal((await db.query('SELECT * FROM public.orders')).rows.length, 0);
  const placed = await checkout(first.id, 'dispatch_001');
  assert.equal(placed.statusCode, 201, placed.body);
  const order = placed.json(); assert.equal(order.status, 'pending_payment'); assert.equal(order.type, 'dispatch');
  assert.equal(order.code_hash, undefined); assert.equal(order.assigned_rider_id, undefined);
  await db.query("UPDATE vendo_internal.dispatch_quotes SET expires_at=now()-interval '1 minute' WHERE id=$1", [first.id]);
  assert.equal((await checkout(first.id, 'dispatch_001')).json().id, order.id);
  assert.equal((await checkout(first.id, 'dispatch_001', 'alice', 'food')).statusCode, 409);
  assert.equal((await checkout(first.id, 'dispatch_002')).statusCode, 409);
  const expired = await quote();
  await db.query("UPDATE vendo_internal.dispatch_quotes SET expires_at=now()-interval '1 minute' WHERE id=$1", [expired.id]);
  assert.equal((await checkout(expired.id, 'expired_key')).statusCode, 409);
  const stale = await quote(); await configure({ ...config, fee_kobo: 12000 });
  assert.equal((await checkout(stale.id, 'stale_package')).statusCode, 409);
  assert.equal((await app.inject({ url: `/v1/orders/${order.id}`, headers: auth() })).json().quote.total_kobo, 56000);
  const cityStale = await quote(); await db.query('UPDATE public.cities SET minimum_delivery_fee_kobo=61501 WHERE id=$1', [cityId]);
  assert.equal((await checkout(cityStale.id, 'stale_city')).statusCode, 409);
  assert.equal((await quote()).total_kobo, 62000);
  const codeRequest = (user = 'alice') => app.inject({ url: `/v1/orders/${order.id}/delivery-code`, headers: auth(user) });
  assert.equal((await codeRequest()).statusCode, 409); assert.equal((await codeRequest('bob')).statusCode, 404);
  assert.equal((await app.inject({ method: 'POST', url: `/v1/vendor/orders/${order.id}/action`, headers: auth('admin'), payload: { action: 'accept' } })).statusCode, 404);
  await assert.rejects(() => accounts.requestDeletion(alice.id, null), /active orders/);
  assert.equal((await app.inject({ method: 'POST', url: `/v1/orders/${order.id}/reorder`, headers: auth() })).statusCode, 409);
  assert.equal((await app.inject({ method: 'POST', url: `/v1/orders/${order.id}/send-again`, headers: auth() })).statusCode, 409);
  await db.query('UPDATE public.orders SET assigned_rider_id=$2 WHERE id=$1', [order.id, rider.id]);
  const storedCode = (await db.query<{ encrypted_code: string }>('SELECT encrypted_code FROM vendo_internal.dispatch_delivery_codes WHERE order_id=$1', [order.id])).rows[0]!;
  const unpaidCode = new DeliveryCodes(secret).decrypt(order.id, storedCode.encrypted_code);
  const premature = await app.inject({ method: 'POST', url: `/v1/rider/orders/${order.id}/confirm-delivery`, headers: auth('rider'), payload: { code: unpaidCode } });
  assert.equal(premature.statusCode, 409);
  assert.equal((await db.query<{ attempts: number }>('SELECT attempts FROM vendo_internal.dispatch_delivery_codes WHERE order_id=$1', [order.id])).rows[0]!.attempts, 0);
  // Assignment/payment/pickup are simulated by trusted SQL until those modules ship.
  await db.query("UPDATE public.orders SET payment_status='paid',status='on_the_way',assigned_rider_id=$2 WHERE id=$1", [order.id, rider.id]);
  const codeResponse = await codeRequest(); assert.equal(codeResponse.statusCode, 200, codeResponse.body);
  const code = codeResponse.json().code as string;
  assert.match(code, /^\d{4}$/); assert.equal((await codeRequest('rider')).statusCode, 404);
  const confirm = (id: string, code: string, user = 'rider') => app.inject({ method: 'POST', url: `/v1/rider/orders/${id}/confirm-delivery`, headers: auth(user), payload: { code } });
  assert.equal((await confirm(order.id, code, 'alice')).statusCode, 403);
  assert.equal((await confirm(order.id, code, 'other-rider')).statusCode, 404);
  assert.equal((await confirm(order.id, code)).statusCode, 200);
  assert.equal((await confirm(order.id, code)).statusCode, 200);
  assert.equal((await codeRequest()).statusCode, 409);
  assert.equal((await db.query('SELECT * FROM public.order_events WHERE order_id=$1', [order.id])).rows.length, 2);
  assert.equal((await app.inject({ url: '/v1/orders?status=past', headers: auth() })).json().items[0].type, 'dispatch');
  const again = await app.inject({ method: 'POST', url: `/v1/orders/${order.id}/send-again`, headers: auth() });
  assert.equal(again.statusCode, 200, again.body); assert.equal(again.json().pickup.landmark, 'Blue gate'); assert.equal(again.json().receiver.phone, bob.phone);
  assert.equal(again.json().total_kobo, undefined);
  assert.equal(again.json().package.prohibited_items_acknowledged, undefined);
  const second = await checkout((await quote()).id, 'dispatch_lock'); assert.equal(second.statusCode, 201, second.body);
  const lockedId = second.json().id;
  await db.query("UPDATE public.orders SET payment_status='paid',status='on_the_way',assigned_rider_id=$2 WHERE id=$1", [lockedId, rider.id]);
  const secondCode = (await app.inject({ url: `/v1/orders/${lockedId}/delivery-code`, headers: auth() })).json().code as string;
  const wrong = ((Number(secondCode) + 1) % 10000).toString().padStart(4, '0');
  for (let attempt = 0; attempt < 2; attempt++) assert.equal((await confirm(lockedId, wrong)).statusCode, 400);
  assert.equal((await confirm(lockedId, wrong)).json().error.code, 'DELIVERY_CODE_LOCKED');
  assert.equal((await confirm(lockedId, secondCode)).statusCode, 409);
  assert.equal((await app.inject({ url: `/v1/orders/${lockedId}`, headers: auth() })).json().status, 'disputed');
  const stored = (await db.query<{ attempts: number; code_hash: string; encrypted_code: string }>('SELECT * FROM vendo_internal.dispatch_delivery_codes WHERE order_id=$1', [lockedId])).rows[0]!;
  assert.equal(stored.attempts, 3); assert.notEqual(stored.code_hash, secondCode); assert.notEqual(stored.encrypted_code, secondCode);
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [bob.id]); await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.orders')).rows.length, 0);
  await assert.rejects(() => db.query('SELECT * FROM vendo_internal.dispatch_delivery_codes'));
  await assert.rejects(() => db.query('SELECT * FROM vendo_internal.dispatch_quotes'));
  await assert.rejects(() => db.query("UPDATE public.dispatch_packages SET fee_kobo=0"));
  await db.exec('RESET ROLE');
  await db.query('UPDATE public.cities SET is_active=false WHERE id=$1', [cityId]);
  assert.equal((await requestQuote()).statusCode, 409);
  assert.equal((await app.inject(`/v1/dispatch/packages?city_id=${cityId}`)).json().items.length, 0);
});
