import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { PostgresPaymentRepository } from '../src/modules/payments/repository.js';
import { PostgresExtrasRepository } from '../src/modules/extras/repository.js';
import { PostgresNotificationRepository } from '../src/modules/notifications/repository.js';
import { NotificationService } from '../src/modules/notifications/service.js';
import { menuInputSchema, vendorInputSchema } from '../src/modules/food/schema.js';
import { packageConfigSchema } from '../src/modules/dispatch/schema.js';
import { promoInput, referralPolicy } from '../src/modules/extras/schema.js';
import { fixtures, alice, bob } from './helpers.js';
test('Customer extras API/SQL: authoritative promos, referrals, support, legal versions, inbox, consent, leases and reminders', async (t) => {
    const db = new PGlite();
    t.after(() => db.close());
    await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
    const dir = new URL('../supabase/migrations/', import.meta.url);
    for (const f of (await readdir(dir)).filter(f => f.endsWith('.sql')).sort())
        await db.exec(await readFile(new URL(f, dir), 'utf8'));
    const query = (sql: string, values?: unknown[]) => db.query(sql, values), pool = { query, connect: async () => ({ query, release() { } }) } as unknown as pg.Pool;
    const profiles = new PostgresProfileRepository(pool), food = new PostgresFoodRepository(pool), dispatch = new PostgresDispatchRepository(pool), accounts = new PostgresAccountRepository(pool), payments = new PostgresPaymentRepository(pool), extras = new PostgresExtrasRepository(pool), notifications = new PostgresNotificationRepository(pool);
    const admin = { id: randomUUID(), phone: '+2348011111111' };
    for (const p of [alice, bob, admin]) {
        await db.query('INSERT INTO auth.users(id) VALUES($1)', [p.id]);
        await profiles.bootstrap(p.id, p.phone);
        await profiles.setName(p.id, 'Test User');
        await profiles.setEmail(p.id, `${p.id}@example.com`);
    }
    await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [admin.id]);
    const city = (await db.query<{
        id: string;
    }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
    await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1', [city, JSON.stringify([{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }])]);
    const vendor = await food.saveVendor(admin.id, vendorInputSchema.parse({ name: 'Kitchen', category: 'restaurant', city_id: city, address: 'Pickup', location: { lat: 10.5, lng: 7.5 }, is_open: true }));
    const menu = await food.saveMenu(admin.id, vendor.id, menuInputSchema.parse({ name: 'Rice', category: 'Meals', price_kobo: 250000 }));
    await dispatch.savePackage(admin.id, city, packageConfigSchema.parse({ size: 'small', label: 'Small', fee_kobo: 10000, max_weight_g: 5000, max_length_cm: 40, max_width_cm: 30, max_height_cm: 30 }));
    const fx = fixtures(), original = fx.dependencies.auth.authenticate;
    fx.dependencies.auth.authenticate = async (token) => token === 'admin' ? admin : original(token);
    const app = await buildApp(readEnv({ NODE_ENV: 'test', DISPATCH_DELIVERY_CODE_SECRET: 'extras-test-delivery-secret-at-least-32-characters' }), { ...fx.dependencies, profiles, food, dispatch, accounts, payments, extras, notifications });
    t.after(() => app.close());
    const headers = (u = 'alice') => ({ authorization: `Bearer ${u}` });
    const post = (url: string, payload: unknown = {}, u = 'alice') => app.inject({ method: 'POST', url, headers: headers(u), payload: payload as Record<string, unknown> });
    const get = (url: string, u = 'alice') => app.inject({ url, headers: headers(u) });
    const put = (url: string, payload: unknown, u = 'admin') => app.inject({ method: 'PUT', url, headers: headers(u), payload: payload as Record<string, unknown> });
    const base = { active: true, starts_at: new Date(Date.now() - 60000).toISOString(), ends_at: new Date(Date.now() + 86400000).toISOString(), scope: 'all' as const, city_id: null, vendor_id: null, basis: 'delivery' as const, kind: 'percent' as const, value: 2500, max_discount_kobo: 20000, minimum_total_kobo: 1, max_uses: 2, per_customer_limit: 1 };
    assert.equal((await app.inject({ url: '/v1/me/notifications' })).statusCode, 401);
    assert.equal((await post('/v1/admin/promos', { code: 'SAVE25', ...base })).statusCode, 403);
    const campaign = await post('/v1/admin/promos', { code: 'save25', ...base }, 'admin');
    assert.equal(campaign.statusCode, 201, campaign.body);
    assert.equal(campaign.json().code, 'SAVE25');
    assert.equal((await post('/v1/admin/promos', { code: 'SAVE25', ...base }, 'admin')).statusCode, 409);
    let seq = 0;
    const quote = async (type = 'food', u = 'alice', code?: string) => {
        const payload = type === 'food' ? { type, vendor_id: vendor.id, items: [{ menu_item_id: menu.id, quantity: 1 }], dropoff: { lat: 10.6, lng: 7.6, address: 'Dropoff' } } : { type, city_id: city, pickup: { lat: 10.5, lng: 7.5, address: 'Pickup' }, dropoff: { lat: 10.6, lng: 7.6, address: 'Dropoff' }, package: { size: 'small', description: 'Shoes', fits_size: true, prohibited_items_acknowledged: true }, receiver: { name: 'Receiver', phone: bob.phone } };
        return post('/v1/orders/quote', { ...payload, ...(code ? { promo_code: code } : {}) }, u);
    };
    const book = (q: string, u = 'alice', key = `extras_booking_${++seq}`, type = 'food') => app.inject({ method: 'POST', url: '/v1/orders', headers: { ...headers(u), 'idempotency-key': key }, payload: { type, quote_id: q, payment_method: 'wallet' } });
    const noPromo = await quote();
    assert.equal(noPromo.statusCode, 200, noPromo.body);
    const discounted = await quote('food', 'alice', 'save25');
    assert.equal(discounted.statusCode, 200, discounted.body);
    assert.equal(discounted.json().discount_kobo, 11250);
    assert.equal(discounted.json().subtotal_kobo, noPromo.json().subtotal_kobo);
    assert.equal(discounted.json().total_kobo, noPromo.json().total_kobo - 11250);
    const staleCap = (await quote('dispatch', 'alice', 'SAVE25')).json();
    const first = await book(discounted.json().id, 'alice', 'extras_same_booking');
    assert.equal(first.statusCode, 201, first.body);
    assert.equal((await book(discounted.json().id, 'alice', 'extras_same_booking')).json().id, first.json().id);
    assert.equal((await book(staleCap.id, 'alice', undefined, 'dispatch')).json().error.code, 'PROMO_LIMIT_REACHED');
    assert.equal((await quote('food', 'alice', 'SAVE25')).statusCode, 409);
    assert.equal((await db.query('SELECT * FROM vendo_internal.promo_redemptions')).rows.length, 1);
    const bobQuote = (await quote('dispatch', 'bob', 'SAVE25')).json();
    assert.equal(bobQuote.discount_kobo, 13750);
    const disabled = await put(`/v1/admin/promos/${campaign.json().id}`, { code: 'SAVE25', ...base, active: false });
    assert.equal(disabled.statusCode, 200, disabled.body);
    assert.equal((await book(bobQuote.id, 'bob', undefined, 'dispatch')).statusCode, 409);
    await put(`/v1/admin/promos/${campaign.json().id}`, { code: 'SAVE25', ...base, value: 5000 });
    assert.equal((await book(bobQuote.id, 'bob', undefined, 'dispatch')).json().error.code, 'PROMO_CHANGED');
    await put(`/v1/admin/promos/${campaign.json().id}`, { code: 'SAVE25', ...base });
    const second = await book(bobQuote.id, 'bob', undefined, 'dispatch');
    assert.equal(second.statusCode, 201, second.body);
    assert.equal((await extras.promos(admin.id))[0]!.used_count, 2);
    const another = promoInput.parse({ code: 'FIXED', ...base, scope: 'food', basis: 'food_subtotal', kind: 'fixed', value: 500000, max_discount_kobo: 500000, max_uses: 10 });
    await extras.savePromo(admin.id, another);
    const fixed = (await quote('food', 'alice', 'FIXED')).json();
    assert.equal(fixed.discount_kobo, 250000);
    assert.equal(fixed.total_kobo, 45000);
    assert.equal((await quote('dispatch', 'alice', 'FIXED')).statusCode, 409);
    // Net quote amount controls wallet checkout; no provider or client amount is involved.
    await db.query('INSERT INTO public.wallets(customer_id,balance_kobo) VALUES ($1,1000000)', [alice.id]);
    const charged = await post(`/v1/orders/${first.json().id}/pay/wallet`);
    assert.equal(charged.statusCode, 200, charged.body);
    assert.equal((await payments.wallet(alice.id)).balance_kobo, 1000000 - discounted.json().total_kobo);
    await post(`/v1/orders/${first.json().id}/pay/wallet`);
    assert.equal((await payments.wallet(alice.id)).balance_kobo, 1000000 - discounted.json().total_kobo);
    // Support is private, idempotent and audited; only admins can resolve/reply as support.
    const ticketBody = { subject: 'Need help with delivery', message: 'Please help me understand this delivery.', category: 'order', order_id: first.json().id };
    const create = () => app.inject({ method: 'POST', url: '/v1/me/support/tickets', headers: { ...headers(), 'idempotency-key': 'support_same_key' }, payload: ticketBody });
    const ticket = await create();
    assert.equal(ticket.statusCode, 201, ticket.body);
    assert.equal((await create()).json().id, ticket.json().id);
    assert.equal((await get(`/v1/me/support/tickets/${ticket.json().id}`, 'bob')).statusCode, 404);
    assert.equal((await post(`/v1/admin/support/tickets/${ticket.json().id}/messages`, { message: 'We are reviewing this delivery.' })).statusCode, 403);
    assert.equal((await post(`/v1/admin/support/tickets/${ticket.json().id}/messages`, { message: 'We are reviewing this delivery.' }, 'admin')).statusCode, 200);
    assert.equal((await get(`/v1/me/support/tickets/${ticket.json().id}`)).json().messages.length, 2);
    assert.equal((await post(`/v1/admin/support/tickets/${ticket.json().id}/resolve`, {}, 'admin')).statusCode, 200);
    assert.equal((await post(`/v1/me/support/tickets/${ticket.json().id}/messages`, { message: 'Reply after closing' })).statusCode, 409);
    // Legal content is supplied by the business, versioned and public; acceptance cannot be forged.
    assert.equal((await get('/v1/legal/privacy')).statusCode, 404);
    const legal = await post('/v1/admin/legal', { slug: 'privacy', version: 'test-v1', title: 'Test privacy policy', content: 'Test-only policy content for integration verification.' }, 'admin');
    assert.equal(legal.statusCode, 201, legal.body);
    assert.equal((await app.inject({ url: '/v1/legal/privacy' })).json().id, legal.json().id);
    await post(`/v1/me/legal/${legal.json().id}/accept`);
    await post(`/v1/me/legal/${legal.json().id}/accept`);
    assert.equal((await db.query('SELECT * FROM public.legal_acceptances')).rows.length, 1);
    // Inbox notifications are atomic with source events; token values are never returned.
    const inbox = await get('/v1/me/notifications');
    assert.equal(inbox.statusCode, 200, inbox.body);
    assert.ok(inbox.json().items.some((n: {
        kind: string;
    }) => n.kind === 'support'));
    assert.ok(inbox.json().unread > 0);
    const n = inbox.json().items[0];
    assert.equal((await post(`/v1/me/notifications/${n.id}/read`, {}, 'bob')).statusCode, 404);
    await post(`/v1/me/notifications/${n.id}/read`);
    assert.equal((await get('/v1/me/notifications')).json().unread, inbox.json().unread - 1);
    await post('/v1/me/notifications/read-all');
    assert.equal((await get('/v1/me/notifications')).json().unread, 0);
    const token = 'test_FCM_registration_token_0123456789';
    const device = await post('/v1/me/devices', { token, platform: 'android' });
    assert.equal(device.statusCode, 200, device.body);
    const pushBody = { profile_ids: [alice.id, bob.id], title: 'Service update', body: 'New stores are available.' };
    const sendPush = (payload = pushBody, u = 'admin', key = 'admin_push_test_01') => app.inject({ method: 'POST', url: '/v1/admin/notifications/push', headers: { ...headers(u), 'idempotency-key': key }, payload });
    assert.equal((await sendPush(pushBody, 'alice')).statusCode, 403);
    const push = await sendPush();
    assert.equal(push.statusCode, 202, push.body);
    assert.equal(push.json().recipients, 2);
    assert.equal(push.json().queued_pushes, 1);
    assert.deepEqual((await sendPush()).json(), push.json());
    assert.equal((await sendPush({ ...pushBody, body: 'Different message' })).statusCode, 409);
    assert.equal((await sendPush({ ...pushBody, profile_ids: [alice.id, alice.id] })).statusCode, 400);
    assert.equal((await sendPush({ ...pushBody, profile_ids: [alice.id, randomUUID()] }, 'admin', 'admin_push_invalid')).statusCode, 400);
    assert.equal((await db.query<{ n: number }>("SELECT count(*)::int AS n FROM public.notifications WHERE dedupe_key LIKE '%admin_push_invalid'")).rows[0]!.n, 0);
    const channels = (await db.query<{ channel: string }>('SELECT channel FROM vendo_internal.notification_outbox WHERE notification_id=ANY($1::uuid[])', [push.json().notification_ids])).rows;
    assert.deepEqual(channels.map(r => r.channel), ['push']);
    assert.ok((await get('/v1/me/notifications', 'bob')).json().items.some((item: { kind: string; body: string }) => item.kind === 'admin_push' && item.body === pushBody.body));
    assert.equal(device.json().token, undefined);
    assert.equal((await post('/v1/me/devices', { token, platform: 'android' })).json().id, device.json().id);
    assert.equal((await post('/v1/me/devices', { token, platform: 'ios' }, 'bob')).statusCode, 409);
    assert.equal((await app.inject({ method: 'DELETE', url: `/v1/me/devices/${device.json().id}`, headers: headers('bob') })).statusCode, 404);
    await db.query("SELECT vendo_internal.notify($1,'test-consent','order','Update','Open Vendo for details.')", [alice.id]);
    // Unverified email and opt-out SMS/WhatsApp are skipped; push retries without affecting orders.
    const sent: string[] = [], service = new NotificationService(notifications, { email: { async send(m) { sent.push(`email:${m.to}`); } }, sms: { async sendText() { sent.push('sms'); } }, whatsapp: { async sendText() { sent.push('wa'); } }, push: { async send() { sent.push('push'); return 'sent'; } } });
    await service.process(100);
    assert.deepEqual(sent, ['push', 'push']);
    await db.query('UPDATE public.profiles SET email_verified=true WHERE id=$1', [alice.id]);
    await accounts.updatePreferences(alice.id, { sms_enabled: true, whatsapp_opt_in: true, push_enabled: false });
    const optedOut = await sendPush({ ...pushBody, profile_ids: [alice.id] }, 'admin', 'admin_push_opted_out');
    assert.equal(optedOut.statusCode, 202, optedOut.body);
    assert.equal(optedOut.json().queued_pushes, 0);
    await db.query("SELECT vendo_internal.notify($1,'test-opt-in','order','Update','Open Vendo for details.')", [alice.id]);
    await service.process(100);
    assert.equal(sent.filter(s => s.startsWith('email:')).length, 1);
    assert.equal(sent.filter(s => s === 'sms').length, 1);
    assert.equal(sent.filter(s => s === 'wa').length, 1);
    await accounts.updatePreferences(alice.id, { push_enabled: true });
    await db.query("SELECT vendo_internal.notify($1,'test-failure','order','Update','Open Vendo for details.')", [alice.id]);
    const broken = new NotificationService(notifications, { push: { async send() { throw new Error('provider secret should not persist'); } } });
    await broken.process(100);
    const failed = (await db.query<{
        id: string;
        attempts: number;
        status: string;
        last_error: string;
    }>("SELECT q.* FROM vendo_internal.notification_outbox q JOIN public.notifications n ON n.id=q.notification_id WHERE n.dedupe_key='test-failure' AND channel='push'")).rows[0]!;
    assert.equal(failed.status, 'pending');
    assert.equal(failed.attempts, 1);
    assert.equal(failed.last_error, 'delivery_unavailable');
    await db.query('UPDATE vendo_internal.notification_outbox SET available_at=now() WHERE id=$1', [failed.id]);
    const lease = (await notifications.claim(1))[0]!;
    await db.query("UPDATE vendo_internal.notification_outbox SET lease_until=now()-interval '1 second' WHERE id=$1", [lease.id]);
    const newer = (await notifications.claim(1))[0]!;
    assert.notEqual(newer.lease_id, lease.lease_id);
    await notifications.finish(lease, 'sent');
    assert.equal((await db.query<{
        status: string;
    }>('SELECT status FROM vendo_internal.notification_outbox WHERE id=$1', [lease.id])).rows[0]!.status, 'sending');
    await notifications.finish(newer, 'sent');
    // Canceled/rescheduled reminders are not delivered; repeated sweeps enqueue once.
    const scheduled = await book((await quote()).json().id);
    const sid = scheduled.json().id;
    await db.query("UPDATE public.orders SET status='scheduled',payment_status='paid',scheduled_at=now()+interval '20 minutes',processing_due_at=now()+interval '10 minutes' WHERE id=$1", [sid]);
    assert.equal(await notifications.reminders(10, 30), 1);
    assert.equal(await notifications.reminders(10, 30), 0);
    await db.query('UPDATE public.orders SET scheduled_at=scheduled_at+interval \'1 hour\',processing_due_at=processing_due_at+interval \'1 hour\' WHERE id=$1', [sid]);
    let checkedReminders = 0;
    const reminderJobs = await notifications.claim(100);
    for (const j of reminderJobs) {
        if (j.notification_id === (await db.query<{
            id: string;
        }>("SELECT id FROM public.notifications WHERE order_id=$1 AND kind='reminder'", [sid])).rows[0]!.id) {
            assert.equal(await notifications.target(j), null);
            checkedReminders++;
        }
        await notifications.finish(j, 'skipped');
    }
    assert.ok(checkedReminders > 0);
    // Referral campaign starts disabled, rejects existing customers, self/cycles and unverified accounts.
    const acode = (await extras.referrals(alice.id)).code, bcode = (await extras.referrals(bob.id)).code;
    assert.equal((await extras.referrals(alice.id)).enabled, false);
    const fresh = { id: randomUUID(), phone: '+2348022222222' };
    await db.query('INSERT INTO auth.users(id) VALUES($1)', [fresh.id]);
    await profiles.bootstrap(fresh.id, fresh.phone);
    await profiles.setName(fresh.id, 'New Customer');
    await profiles.setEmail(fresh.id, 'fresh@example.com');
    await assert.rejects(() => extras.applyReferral(fresh.id, acode), /verified emails/);
    await db.query('UPDATE public.profiles SET email_verified=true WHERE id=ANY($1::uuid[])', [[bob.id, fresh.id]]);
    const policy = referralPolicy.parse({ enabled: true, referrer_reward_kobo: 1000, referee_reward_kobo: 500, minimum_order_kobo: 10000, hold_days: 1, expiry_days: 30, referrer_cap: 1 });
    await extras.setReferralPolicy(admin.id, policy);
    await assert.rejects(() => extras.applyReferral(bob.id, acode), /before placing/);
    await assert.rejects(() => extras.applyReferral(alice.id, acode), /cannot be applied/);
    await extras.applyReferral(fresh.id, acode);
    await extras.applyReferral(fresh.id, acode);
    await assert.rejects(() => extras.applyReferral(fresh.id, bcode), /already applied/);
    const ref = (await db.query<{
        id: string;
    }>('SELECT id FROM vendo_internal.referrals WHERE referee_id=$1', [fresh.id])).rows[0]!;
    await assert.rejects(() => accounts.requestDeletion(fresh.id, null), /pending referral/);
    assert.equal(await extras.rewardReferrals(10), 0);
    // Controlled SQL fixture advances delivery time, exercising the real atomic reward ledger.
    const freshOrder = await food.createOrder(fresh.id, (await food.saveQuote(fresh.id, noPromo.json(), (await food.getCity(city))!.pricing_version)).id, 'wallet', 'fresh_referral_order');
    await db.query("UPDATE public.orders SET status='delivered',payment_status='paid',delivered_at=now()-interval '2 days' WHERE id=$1", [freshOrder.id]);
    await extras.setReferralPolicy(admin.id, { ...policy, enabled: false });
    assert.equal(await extras.rewardReferrals(10), 0);
    await extras.setReferralPolicy(admin.id, { ...policy, referrer_reward_kobo: 2000 });
    const before = (await payments.wallet(alice.id)).balance_kobo;
    await db.query('INSERT INTO public.wallets(customer_id,balance_kobo) VALUES ($1,9000000000000)', [fresh.id]);
    await assert.rejects(() => extras.rewardReferrals(10), /balance limit/);
    assert.equal((await payments.wallet(alice.id)).balance_kobo, before);
    assert.equal((await db.query('SELECT * FROM public.wallet_transactions WHERE referral_id=$1', [ref.id])).rows.length, 0);
    await db.query('UPDATE public.wallets SET balance_kobo=0 WHERE customer_id=$1', [fresh.id]);
    assert.equal(await extras.rewardReferrals(10), 1);
    assert.equal(await extras.rewardReferrals(10), 0);
    assert.equal((await payments.wallet(alice.id)).balance_kobo, before + 1000);
    assert.equal((await payments.wallet(fresh.id)).balance_kobo, 500);
    assert.equal((await db.query('SELECT * FROM public.wallet_transactions WHERE referral_id=$1', [ref.id])).rows.length, 2);
    assert.equal((await payments.history(fresh.id, 20, 0))[0]!.kind, 'referral');
    const newCustomer = async (phone: string, email: string) => { const id = randomUUID(); await db.query('INSERT INTO auth.users(id) VALUES($1)', [id]); await profiles.bootstrap(id, phone); await profiles.setName(id, 'New Customer'); await profiles.setEmail(id, email); await db.query('UPDATE public.profiles SET email_verified=true WHERE id=$1', [id]); return id; };
    const c1 = await newCustomer('+2348033333333', 'cycle1@example.com'), c2 = await newCustomer('+2348044444444', 'cycle2@example.com');
    await assert.rejects(() => extras.applyReferral(c1, acode), /limit/);
    const c1code = (await extras.referrals(c1)).code, c2code = (await extras.referrals(c2)).code;
    await extras.applyReferral(c1, c2code);
    await assert.rejects(() => extras.applyReferral(c2, c1code), /Circular/);
    await db.query("UPDATE vendo_internal.referrals SET created_at=now()-interval '31 days' WHERE referee_id=$1", [c1]);
    assert.equal(await extras.rewardReferrals(10), 0);
    assert.equal((await extras.referrals(c2)).pending, 0);
    await db.query("SELECT vendo_internal.notify($1,'invalid-device-test','order','Update','Open Vendo for details.')", [alice.id]);
    await new NotificationService(notifications, { push: { async send() { return 'invalid'; } } }).process(100);
    assert.equal((await notifications.devices(alice.id)).length, 0);
    // Missing matching policy inserts a no-rider state directly and must still notify.
    await db.query("UPDATE public.orders SET status='searching_rider',payment_status='paid' WHERE id=$1",[second.json().id]);
    await db.query("INSERT INTO vendo_internal.matching_searches(order_id,state,deadline_at,radius_m,reason) VALUES($1,'no_rider',now(),0,'matching_not_configured')",[second.json().id]);
    assert.equal((await db.query("SELECT id FROM public.notifications WHERE order_id=$1 AND kind='no_rider'",[second.json().id])).rows.length,1);
    // RLS clients can only read their own inbox/support and cannot mutate campaign money or raw tokens.
    await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [alice.id]);
    await db.exec('SET ROLE authenticated');
    assert.ok((await db.query<{
        profile_id: string;
    }>('SELECT * FROM public.notifications')).rows.every(r => r.profile_id === alice.id));
    assert.equal((await db.query('SELECT * FROM public.support_tickets')).rows.length, 1);
    await assert.rejects(() => db.query('SELECT * FROM vendo_internal.devices'));
    await assert.rejects(() => db.query("UPDATE public.notifications SET read_at=now()"));
    await assert.rejects(() => db.query('SELECT * FROM vendo_internal.referrals'));
    await db.exec('RESET ROLE;SET ROLE anon');
    assert.equal((await db.query('SELECT * FROM public.legal_pages')).rows.length, 1);
    await assert.rejects(() => db.query('SELECT * FROM public.notifications'));
    await db.exec('RESET ROLE');
});
