import assert from 'node:assert/strict';
import { test } from 'node:test';
import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { ApiError } from '../src/lib/errors.js';
import { readEnv } from '../src/config/env.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { deliveryFee, insidePolygon, cityOpen } from '../src/modules/food/pricing.js';
import type { CityPricing } from '../src/modules/food/schema.js';
import { fixtures, alice, bob } from './helpers.js';

const boundary = [{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }];
test('delivery fees round up in kobo, respect minimums, and service hours include overnight windows', () => {
  const city = { base_fare_kobo: '30000', per_km_rate_kobo: '10000', minimum_delivery_fee_kobo: '0', opens_at: '22:00:00', closes_at: '06:00:00' } as CityPricing;
  assert.equal(deliveryFee(city, 1501), 46000);
  assert.equal(deliveryFee({ ...city, minimum_delivery_fee_kobo: '60501' }, 1), 61000);
  assert.throws(() => deliveryFee({ ...city, base_fare_kobo: null }, 1), /not configured/);
  assert.equal(insidePolygon({ lat: 10.5, lng: 7.5 }, boundary), true);
  assert.equal(insidePolygon({ lat: 10, lng: 7.5 }, boundary), true);
  assert.equal(insidePolygon({ lat: 12, lng: 7.5 }, boundary), false);
  assert.equal(cityOpen(city, new Date('2026-10-03T22:00:00Z')), true);
  assert.equal(cityOpen(city, new Date('2026-10-03T12:00:00Z')), false);
});

test('Food Court database and API: catalog, options, quotes, checkout retries, privacy and fulfillment', async (t) => {
  const db = new PGlite();
  t.after(() => db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users (id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  for (const file of ['202610030001_accounts.sql', '202610030002_account_controls.sql', '202610030003_food_court.sql', '202610030004_dispatch.sql', '202610030005_addresses_maps.sql', '202610030006_orders.sql', '202610030007_payments_wallet.sql', '202610030008_matching_tracking.sql', '202610030009_notifications_extras.sql', '202610030010_operations_finance_chat.sql','202610030011_media_storage.sql','202610030012_vendor_registration.sql','202610060013_vendor_portal.sql']) {
    await db.exec(await readFile(new URL(`../supabase/migrations/${file}`, import.meta.url), 'utf8'));
  }
  const query = (sql: string, values?: unknown[]) => db.query(sql, values);
  const pool = { query, connect: async () => ({ query, release() {} }) } as unknown as pg.Pool;
  const profiles = new PostgresProfileRepository(pool);
  const food = new PostgresFoodRepository(pool);
  const accounts = new PostgresAccountRepository(pool);
  const admin = { id: randomUUID(), phone: '+2348011111111' };
  const staff = { id: randomUUID(), phone: '+2348022222222' };
  const stranger = { id: randomUUID(), phone: '+2348033333333' };
  for (const identity of [alice, bob, admin, staff, stranger]) {
    await db.query('INSERT INTO auth.users (id) VALUES ($1)', [identity.id]);
    await profiles.bootstrap(identity.id, identity.phone);
    await profiles.setName(identity.id, 'Test User');
    await profiles.setEmail(identity.id, `${identity.id}@example.com`);
  }
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [admin.id]);
  await db.query("UPDATE public.profiles SET role='vendor_staff' WHERE id=ANY($1::uuid[])", [[staff.id, stranger.id]]);
  const cityId = (await db.query<{ id: string }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
  await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1', [cityId, JSON.stringify(boundary)]);
  const fixture = fixtures();
  const originalAuth = fixture.dependencies.auth.authenticate;
  fixture.dependencies.auth.authenticate = async (token) => token === 'admin' ? admin : token === 'staff' ? staff : token === 'stranger' ? stranger : originalAuth(token);
  const app = await buildApp(readEnv({ NODE_ENV: 'test' }), { ...fixture.dependencies, food, profiles, accounts });
  t.after(() => app.close());
  const headers = { authorization: 'Bearer alice' };
  const vendorInput = { name: 'Test Kitchen', category: 'restaurant', city_id: cityId, address: 'Test pickup', location: { lat: 10.5, lng: 7.5 }, is_open: true };
  assert.equal((await app.inject({ method: 'POST', url: '/v1/admin/vendors', headers, payload: vendorInput })).statusCode, 403);
  const createdVendor = await app.inject({ method: 'POST', url: '/v1/admin/vendors', headers: { authorization: 'Bearer admin' }, payload: vendorInput });
  assert.equal(createdVendor.statusCode, 201, createdVendor.body);
  const vendorId = createdVendor.json().id;
  const optionId = randomUUID();
  const menuInput = { name: 'Jollof rice', category: 'Meals', price_kobo: 250000, option_groups: [{ id: randomUUID(), name: 'Protein', min: 1, max: 1, options: [{ id: optionId, name: 'Chicken', price_kobo: 100000 }] }] };
  const createdMenu = await app.inject({ method: 'POST', url: `/v1/admin/vendors/${vendorId}/menu`, headers: { authorization: 'Bearer admin' }, payload: menuInput });
  assert.equal(createdMenu.statusCode, 201, createdMenu.body);
  const itemId = createdMenu.json().id;
  const list = await app.inject(`/v1/vendors?city_id=${cityId}&q=jollof&lat=10.5&lng=7.5`);
  assert.equal(list.statusCode, 200, list.body);
  assert.equal(list.json().total, 1);
  assert.equal(list.json().items[0].distance_m, 0);
  assert.equal((await app.inject(`/v1/vendors?city_id=${cityId}&q=%25`)).json().total, 0);
  assert.equal((await app.inject(`/v1/vendors/${vendorId}`)).json().menu.length, 1);
  const cart = { vendor_id: vendorId, items: [{ menu_item_id: itemId, quantity: 2, option_ids: [optionId] }] };
  const validate = (payload: Record<string, unknown>) => app.inject({ method: 'POST', url: '/v1/food/cart/validate', headers, payload });
  assert.equal((await validate(cart)).json().subtotal_kobo, 700000);
  assert.equal((await validate({ ...cart, subtotal_kobo: 1 })).statusCode, 400);
  assert.equal((await validate({ ...cart, items: [{ menu_item_id: itemId, quantity: 1 }] })).statusCode, 400);
  assert.equal((await validate({ ...cart, items: [{ menu_item_id: itemId, quantity: 1, option_ids: [optionId, optionId] }] })).statusCode, 400);
  assert.equal((await validate({ ...cart, items: [{ menu_item_id: randomUUID(), quantity: 1 }] })).statusCode, 409);
  const quoteInput = { ...cart, type: 'food', dropoff: { lat: 10.6, lng: 7.6, address: 'Test delivery' } };
  const quote = async () => {
    const response = await app.inject({ method: 'POST', url: '/v1/orders/quote', headers, payload: quoteInput });
    assert.equal(response.statusCode, 200, response.body); return response.json();
  };
  assert.equal((await app.inject({ method: 'POST', url: '/v1/orders/quote', headers, payload: { ...quoteInput, dropoff: { lat: 12, lng: 7.6, address: 'Outside' } } })).statusCode, 400);
  await db.query('UPDATE public.cities SET service_polygon=NULL WHERE id=$1', [cityId]);
  assert.equal((await app.inject({ method: 'POST', url: '/v1/orders/quote', headers, payload: quoteInput })).statusCode, 503);
  await db.query('UPDATE public.cities SET service_polygon=$2 WHERE id=$1', [cityId, JSON.stringify(boundary)]);
  const realRoute = fixture.dependencies.routing.route;
  fixture.dependencies.routing.route = async () => { throw new ApiError(503, 'ROUTING_UNAVAILABLE', 'Routes unavailable'); };
  assert.equal((await app.inject({ method: 'POST', url: '/v1/orders/quote', headers, payload: quoteInput })).statusCode, 503);
  fixture.dependencies.routing.route = realRoute;
  await db.query("UPDATE public.profiles SET email=NULL WHERE id=$1", [bob.id]);
  assert.equal((await app.inject({ method: 'POST', url: '/v1/orders/quote', headers: { authorization: 'Bearer bob' }, payload: quoteInput })).statusCode, 403);
  await profiles.setEmail(bob.id, 'bob@example.com');
  const firstQuote = await quote();
  assert.equal(firstQuote.delivery_fee_kobo, 45000);
  assert.equal(firstQuote.total_kobo, 745000);
  const checkout = (quoteId: string, key: string, user = 'alice', method = 'card') => app.inject({ method: 'POST', url: '/v1/orders', headers: { authorization: `Bearer ${user}`, 'idempotency-key': key }, payload: { quote_id: quoteId, payment_method: method } });
  assert.equal((await checkout(firstQuote.id, 'foreign_key', 'bob')).statusCode, 409);
  const createdOrder = await checkout(firstQuote.id, 'checkout_001');
  assert.equal(createdOrder.statusCode, 201, createdOrder.body);
  const order = createdOrder.json();
  assert.equal(order.status, 'pending_payment');
  assert.equal(order.payment_status, 'unpaid');
  assert.equal(order.customer_id, undefined);
  await db.query("UPDATE vendo_internal.food_quotes SET expires_at=now()-interval '1 minute' WHERE id=$1", [firstQuote.id]);
  assert.equal((await checkout(firstQuote.id, 'checkout_001')).json().id, order.id);
  assert.equal((await checkout(firstQuote.id, 'checkout_001', 'alice', 'wallet')).statusCode, 409);
  assert.equal((await checkout(firstQuote.id, 'checkout_002')).statusCode, 409);
  assert.equal((await app.inject({ url: `/v1/orders/${order.id}`, headers: { authorization: 'Bearer bob' } })).statusCode, 404);
  assert.equal((await app.inject({ url: '/v1/orders', headers })).json().items.length, 1);
  await assert.rejects(() => accounts.requestDeletion(alice.id, null), /active orders/);
  const stalePrice = await quote();
  await db.query('UPDATE public.menu_items SET price_kobo=260000 WHERE id=$1', [itemId]);
  assert.equal((await checkout(stalePrice.id, 'stale_price')).statusCode, 409);
  assert.equal((await app.inject({ url: `/v1/orders/${order.id}`, headers })).json().quote.subtotal_kobo, 700000);
  const staleCity = await quote();
  await db.query('UPDATE public.cities SET per_km_rate_kobo=11000 WHERE id=$1', [cityId]);
  assert.equal((await checkout(staleCity.id, 'stale_city')).statusCode, 409);
  const action = (user: string, op: string) => app.inject({ method: 'POST', url: `/v1/vendor/orders/${order.id}/action`, headers: { authorization: `Bearer ${user}` }, payload: { action: op } });
  await food.assignStaff(admin.id, vendorId, staff.id);
  assert.equal((await action('alice', 'accept')).statusCode, 403);
  assert.equal((await action('stranger', 'accept')).statusCode, 404);
  assert.equal((await action('staff', 'accept')).statusCode, 409);
  // Simulate the future verified payment worker, never a public payment bypass.
  await db.query("UPDATE public.orders SET payment_status='paid',status='awaiting_vendor' WHERE id=$1", [order.id]);
  assert.equal((await action('staff', 'accept')).json().status, 'searching_rider');
  assert.equal((await action('staff', 'accept')).json().status, 'searching_rider');
  assert.equal((await action('staff', 'ready')).statusCode, 200);
  assert.equal((await action('staff', 'reject')).statusCode, 409);
  assert.equal((await db.query('SELECT * FROM public.order_events WHERE order_id=$1', [order.id])).rows.length, 2);
  const rejectOrder = await checkout((await quote()).id, 'reject_order');
  assert.equal(rejectOrder.statusCode, 201, rejectOrder.body);
  await db.query("UPDATE public.orders SET payment_status='paid',status='awaiting_vendor' WHERE id=$1", [rejectOrder.json().id]);
  const rejected = await food.vendorAction(staff.id, rejectOrder.json().id, 'reject');
  assert.equal(rejected.refund_status, 'pending');
  assert.equal((await app.inject({ method: 'POST', url: `/v1/orders/${rejected.id}/reorder`, headers })).json().subtotal_kobo, 720000);
  await db.query("UPDATE public.orders SET status='delivered' WHERE id=$1", [order.id]);
  await assert.rejects(() => accounts.requestDeletion(alice.id, null), /pending refunds/);
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [bob.id]);
  await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.orders')).rows.length, 0);
  await assert.rejects(() => db.query("UPDATE public.orders SET payment_status='paid'"));
  await db.exec('RESET ROLE; SET ROLE anon');
  await assert.rejects(() => db.query('SELECT * FROM vendo_internal.food_quotes'));
  await db.exec('RESET ROLE');
  await db.query('UPDATE public.vendors SET is_active=false WHERE id=$1', [vendorId]);
  assert.equal((await app.inject(`/v1/vendors?city_id=${cityId}`)).json().total, 0);
  assert.equal((await app.inject(`/v1/vendors/${vendorId}`)).statusCode, 404);
});
