import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile,readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { PostgresOrderRepository } from '../src/modules/orders/repository.js';
import { PostgresPaymentRepository } from '../src/modules/payments/repository.js';
import { PaymentService } from '../src/modules/payments/service.js';
import { PostgresMatchingRepository } from '../src/modules/matching/repository.js';
import { menuInputSchema,vendorInputSchema } from '../src/modules/food/schema.js';
import { packageConfigSchema } from '../src/modules/dispatch/schema.js';
import { channels,type Intent,type PaymentGateway } from '../src/modules/payments/schema.js';
import { fixtures,alice,bob } from './helpers.js';

test('Matching/tracking API and SQL: eligible riders, durable timed offers, radius expansion, atomic claims, private GPS/ETA, no-rider refund and delivery',async(t)=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  const dir=new URL('../supabase/migrations/',import.meta.url);
  for(const file of (await readdir(dir)).filter(name=>name.endsWith('.sql')).sort())await db.exec(await readFile(new URL(file,dir),'utf8'));
  const query=(sql:string,values?:unknown[])=>db.query(sql,values),pool={query,connect:async()=>({query,release(){}})} as unknown as pg.Pool;
  const profiles=new PostgresProfileRepository(pool),food=new PostgresFoodRepository(pool),dispatch=new PostgresDispatchRepository(pool),orders=new PostgresOrderRepository(pool),payments=new PostgresPaymentRepository(pool),matching=new PostgresMatchingRepository(pool);
  const users={alice,bob,admin:{id:randomUUID(),phone:'+2348011111111'},r1:{id:randomUUID(),phone:'+2348022222222'},r2:{id:randomUUID(),phone:'+2348033333333'},r3:{id:randomUUID(),phone:'+2348044444444'}};
  for(const user of Object.values(users)){await db.query('INSERT INTO auth.users(id) VALUES($1)',[user.id]);await profiles.bootstrap(user.id,user.phone);await profiles.setName(user.id,'Test User');await profiles.setEmail(user.id,`${user.id}@example.com`);}
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1",[users.admin.id]);
  const cities=(await db.query<{id:string;name:string}>("SELECT id,name FROM public.cities WHERE name IN ('Kaduna','Kano')")).rows;
  const cityId=cities.find(city=>city.name==='Kaduna')!.id,otherCity=cities.find(city=>city.name==='Kano')!.id;
  const polygon=[{lat:10,lng:7},{lat:11,lng:7},{lat:11,lng:8},{lat:10,lng:8}];
  // Overlapping test boundaries make city isolation independent of distance.
  for(const city of cities)await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1',[city.id,JSON.stringify(polygon)]);
  const vendor=await food.saveVendor(users.admin.id,vendorInputSchema.parse({name:'Kitchen',category:'restaurant',city_id:cityId,address:'Pickup',location:{lat:10.5,lng:7.5},is_open:true}));
  const menu=await food.saveMenu(users.admin.id,vendor.id,menuInputSchema.parse({name:'Rice',category:'Meals',price_kobo:250000}));
  await dispatch.savePackage(users.admin.id,cityId,packageConfigSchema.parse({size:'small',label:'Small',fee_kobo:10000,max_weight_g:5000,max_length_cm:40,max_width_cm:30,max_height_cm:30}));
  const pending=new Map<string,Intent>();let transactionId=0;
  const gateway:PaymentGateway={async initialize(intent){pending.set(intent.reference,intent);return {reference:intent.reference,authorization_url:'https://checkout.paystack.com/test',access_code:'test'};},async verify(reference){const intent=pending.get(reference)!;return {id:String(++transactionId),reference,status:'success',amount:intent.amount_kobo,currency:'NGN',domain:'test',channel:channels[intent.method],customer:{email:intent.email},metadata:{payment_id:intent.id,customer_id:intent.customer_id,order_id:intent.order_id,purpose:intent.purpose}};},async verifyRefund(){throw new Error('Unused');}};
  const paymentService=new PaymentService(payments,gateway),topup=await paymentService.initialize(alice.id,'matching_test_topup',{amount_kobo:10000000,method:'card'});await paymentService.verify(topup.reference);
  const fixture=fixtures();fixture.dependencies.auth.authenticate=async(token)=>{const user=users[token as keyof typeof users];if(!user)throw new Error('Invalid token');return user;};
  let routingFails=false;
  const app=await buildApp(readEnv({NODE_ENV:'test',DISPATCH_DELIVERY_CODE_SECRET:'matching-test-delivery-code-secret-32-characters'}),{...fixture.dependencies,profiles,food,dispatch,orders,payments,paymentGateway:gateway,matching,routing:{async route(){if(routingFails)throw new Error('Unavailable');return {distance_m:1500,duration_s:300};}}});t.after(()=>app.close());
  const headers=(user='alice')=>({authorization:`Bearer ${user}`});
  const post=(url:string,payload:Record<string,unknown>={},user='alice')=>app.inject({method:'POST',url,headers:headers(user),payload});
  const get=(url:string,user='alice')=>app.inject({url,headers:headers(user)});
  const policy={initial_radius_m:500,max_radius_m:2000,radius_step_m:500,expansion_seconds:5,offer_seconds:5,search_seconds:30,location_max_age_seconds:60,max_accuracy_m:50};
  const savePolicy=(city=cityId,user='admin')=>app.inject({method:'PUT',url:`/v1/admin/cities/${city}/matching-policy`,headers:headers(user),payload:policy});
  const review=(rider='r1',approval='approved',user='admin')=>post(`/v1/admin/riders/${users[rider as keyof typeof users].id}/review`,{approval,note:'Documents reviewed by operations'},user);
  let gpsSequence=0;
  const sample=(lat=10.5002)=>({lat,lng:7.5,accuracy_m:10,heading:90,speed_mps:2,captured_at:new Date(Date.now()+(++gpsSequence)*10).toISOString()});
  const locate=(rider='r1',input=sample())=>post('/v1/riders/me/location',input,rider);
  const online=(rider='r1',value=true)=>post('/v1/riders/me/presence',{online:value},rider);
  const offer=(rider='r1')=>get('/v1/riders/me/offers/current',rider);
  const respond=(id:string,action='accept',rider='r1')=>post(`/v1/riders/offers/${id}/respond`,{action},rider);
  let booking=0;
  const book=async(type='food')=>{
    const input=type==='food'?{type,vendor_id:vendor.id,items:[{menu_item_id:menu.id,quantity:1}],dropoff:{lat:10.6,lng:7.6,address:'Dropoff'}}:{type,city_id:cityId,pickup:{lat:10.5,lng:7.5,address:'Pickup'},dropoff:{lat:10.6,lng:7.6,address:'Dropoff'},package:{size:'small',description:'Shoes',fits_size:true,prohibited_items_acknowledged:true},receiver:{name:'Receiver',phone:bob.phone}};
    const quote=await post('/v1/orders/quote',input);assert.equal(quote.statusCode,200,quote.body);
    const order=await app.inject({method:'POST',url:'/v1/orders',headers:{...headers(),'idempotency-key':`matching_booking_${++booking}`},payload:{type,quote_id:quote.json().id,payment_method:'wallet'}});assert.equal(order.statusCode,201,order.body);return order.json();
  };
  const pay=async(id:string)=>{const result=await post(`/v1/orders/${id}/pay/wallet`);assert.equal(result.statusCode,200,result.body);};
  const track=(id:string,user='alice',route=true)=>get(`/v1/orders/${id}/tracking?include_route=${route}`,user);
  assert.equal((await app.inject({url:'/v1/riders/me'})).statusCode,401);
  for(const rider of ['r1','r2','r3']){
    const registered=await post('/v1/riders/register',{city_id:rider==='r3'?otherCity:cityId,vehicle_type:'motorcycle',plate_number:`KD-${rider}`},rider);assert.equal(registered.statusCode,200,registered.body);assert.equal(registered.json().approval,'pending');
    assert.equal((await online(rider)).statusCode,403);
  }
  assert.equal((await review('r1','approved','alice')).statusCode,403);
  assert.equal((await savePolicy(cityId,'alice')).statusCode,403);
  await review();assert.equal((await online()).statusCode,503);assert.equal((await locate()).statusCode,503);
  for(const city of [cityId,otherCity])assert.equal((await savePolicy(city)).statusCode,200);
  await review('r2');await review('r3');assert.equal((await online()).statusCode,409);
  const initial=sample();assert.equal((await locate('r1',initial)).statusCode,200);assert.equal((await locate('r1',initial)).statusCode,200);
  assert.equal((await locate('r1',{...initial,lat:10.5003})).statusCode,409);
  assert.equal((await locate('r1',{...sample(),captured_at:new Date(Date.now()+60000).toISOString()})).statusCode,400);
  assert.equal((await locate('r1',{...sample(),accuracy_m:100})).statusCode,400);
  assert.equal((await locate('r1',{...sample(),lat:12})).statusCode,400);
  for(const [rider,lat] of [['r1',10.5002],['r2',10.505],['r3',10.50001]] as const){await locate(rider,sample(lat));assert.equal((await online(rider)).statusCode,200);}
  assert.equal((await post('/v1/riders/register',{city_id:cityId,vehicle_type:'car',plate_number:'NEW-CAR'},'r1')).statusCode,409);
  const first=await book();assert.equal((await matching.process(100)).offered,0);await pay(first.id);assert.equal((await matching.process(100)).offered,0);
  await food.vendorAction(users.admin.id,first.id,'accept');assert.equal((await matching.process(100)).offered,1);assert.equal((await matching.process(100)).offered,0);
  const firstOfferResponse=await offer();assert.equal(firstOfferResponse.statusCode,200,firstOfferResponse.body);const one=firstOfferResponse.json();assert.equal(one.order_id,first.id);assert.equal(one.type,'food');assert.equal(one.receiver,undefined);
  assert.equal((await offer('r2')).json(),null);assert.equal((await offer('r3')).json(),null);
  assert.equal((await respond(one.id,'accept','r2')).statusCode,404);
  assert.equal((await respond(one.id,'reject')).json().status,'rejected');assert.equal((await respond(one.id,'reject')).json().status,'rejected');
  assert.equal((await matching.process(100)).offered,0);
  await db.query("UPDATE vendo_internal.matching_searches SET started_at=now()-interval '6 seconds' WHERE order_id=$1",[first.id]);assert.equal((await matching.process(100)).offered,1);
  const two=(await offer('r2')).json();assert.equal(two.order_id,first.id);assert.equal((await track(first.id)).json().matching.radius_m,1000);
  await db.query("UPDATE vendo_internal.rider_offers SET expires_at=now()-interval '1 second' WHERE id=$1",[two.id]);assert.equal((await respond(two.id,'accept','r2')).statusCode,409);assert.equal((await matching.process(100)).expired,1);
  await db.query("UPDATE vendo_internal.matching_searches SET deadline_at=now()-interval '1 second' WHERE order_id=$1",[first.id]);assert.equal((await matching.process(100)).no_rider,1);
  assert.equal((await track(first.id)).json().matching.state,'no_rider');assert.equal((await get(`/v1/admin/matching/queue?city_id=${cityId}`)).statusCode,403);assert.equal((await get(`/v1/admin/matching/queue?city_id=${cityId}`,'admin')).json().items.length,1);
  assert.equal((await post(`/v1/orders/${first.id}/matching/retry`,{},'bob')).statusCode,404);assert.equal((await post(`/v1/orders/${first.id}/matching/retry`)).statusCode,200);await post(`/v1/orders/${first.id}/matching/retry`);
  assert.equal((await matching.process(100)).offered,1);const retried=(await offer()).json();assert.notEqual(retried.id,one.id);
  await db.query("UPDATE vendo_internal.rider_locations SET captured_at=now()-interval '2 minutes',received_at=now()-interval '2 minutes' WHERE rider_id=$1",[users.r1.id]);assert.equal((await respond(retried.id)).statusCode,409);
  const cleaned=await matching.process(100);assert.equal(cleaned.offline,1);assert.equal(cleaned.expired,1);await locate();await online();
  await db.query("UPDATE vendo_internal.matching_searches SET deadline_at=now()-interval '1 second' WHERE order_id=$1",[first.id]);await matching.process(100);
  const noRiderCancel=await post(`/v1/orders/${first.id}/matching/cancel`);assert.equal(noRiderCancel.statusCode,200,noRiderCancel.body);assert.equal(noRiderCancel.json().refund_status,'pending');assert.equal((await post(`/v1/orders/${first.id}/matching/cancel`)).statusCode,200);assert.equal(await payments.refundWallets(100),1);assert.equal((await payments.wallet(alice.id)).balance_kobo,10000000);
  const parcel=await book('dispatch');await pay(parcel.id);assert.equal((await matching.process(100)).offered,1);const parcelOffer=(await offer()).json();
  const next=await book();await pay(next.id);await food.vendorAction(users.admin.id,next.id,'accept');
  await assert.rejects(()=>db.query("INSERT INTO vendo_internal.rider_offers(order_id,rider_id,generation,distance_m,expires_at) VALUES($1,$2,1,1,now()+interval '30 seconds')",[next.id,users.r1.id]));
  const accepted=await respond(parcelOffer.id);assert.equal(accepted.statusCode,200,accepted.body);assert.equal(accepted.json().status,'accepted');assert.equal((await respond(parcelOffer.id)).json().status,'accepted');assert.equal((await respond(parcelOffer.id,'reject')).statusCode,409);
  assert.equal((await get('/v1/riders/me/job','r1')).json().id,parcel.id);assert.equal((await get('/v1/riders/me','r1')).json().presence,'on_trip');
  const tracked=await track(parcel.id);assert.equal(tracked.statusCode,200,tracked.body);assert.equal(tracked.json().rider.phone,users.r1.phone);assert.equal(tracked.json().rider.whatsapp_url,`https://wa.me/${users.r1.phone.slice(1)}`);assert.equal(tracked.json().eta.target,'pickup');assert.equal(tracked.json().location_stale,false);
  assert.equal((await track(parcel.id,'bob')).statusCode,404);assert.equal((await track(parcel.id,'r2')).statusCode,404);assert.equal((await track(parcel.id,'r1')).statusCode,200);
  // Both the API and direct Realtime-friendly RLS allow only participants.
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[bob.id]);await db.exec('SET ROLE authenticated');assert.equal((await db.query('SELECT * FROM public.order_tracking')).rows.length,0);await assert.rejects(()=>db.query('SELECT * FROM vendo_internal.rider_locations'));await assert.rejects(()=>db.query('DELETE FROM public.order_tracking'));await db.exec('RESET ROLE');
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[users.r1.id]);await db.exec('SET ROLE authenticated');assert.equal((await db.query('SELECT * FROM public.order_tracking')).rows.length,1);assert.equal((await db.query('SELECT * FROM public.orders')).rows.length,1);await db.exec('RESET ROLE');
  await assert.rejects(()=>db.query("UPDATE public.orders SET assigned_rider_id=$2,status='rider_assigned' WHERE id=$1",[next.id,users.r1.id]));
  assert.equal((await review('r1','suspended')).statusCode,409);
  assert.equal((await matching.process(100)).offered,0);await db.query("UPDATE vendo_internal.matching_searches SET started_at=now()-interval '6 seconds' WHERE order_id=$1",[next.id]);assert.equal((await matching.process(100)).offered,1);const nextOffer=(await offer('r2')).json();assert.equal((await respond(nextOffer.id,'accept','r2')).statusCode,200);
  await locate('r1',sample(10.55));const changed=await track(parcel.id);assert.equal(changed.json().location.lat,10.55);
  routingFails=true;assert.equal((await track(parcel.id)).json().eta,null);routingFails=false;
  await db.query("UPDATE public.order_tracking SET captured_at=now()-interval '2 minutes' WHERE order_id=$1",[parcel.id]);const stale=await track(parcel.id);assert.equal(stale.json().location_stale,true);assert.equal(stale.json().eta,null);await locate();
  const action=(id:string,status:string,rider='r1')=>post(`/v1/rider/orders/${id}/status`,{action:status},rider);
  assert.equal((await action(parcel.id,'picked_up','r2')).statusCode,404);assert.equal((await action(parcel.id,'picked_up')).statusCode,200);assert.equal((await action(parcel.id,'on_the_way')).statusCode,200);assert.equal((await track(parcel.id)).json().eta.target,'dropoff');assert.equal((await action(parcel.id,'delivered')).statusCode,409);
  const code=(await get(`/v1/orders/${parcel.id}/delivery-code`)).json();
  const complete=await post(`/v1/rider/orders/${parcel.id}/confirm-delivery`,{code:code.code},'r1');assert.equal(complete.statusCode,200,complete.body);
  assert.equal((await get('/v1/riders/me/job','r1')).json(),null);assert.equal((await track(parcel.id)).json().location,null);assert.equal((await track(parcel.id)).json().rider.phone,null);
  const streamed=await get(`/v1/orders/${parcel.id}/tracking/stream`);assert.equal(streamed.statusCode,200,streamed.body);assert.match(streamed.headers['content-type'] as string,/text\/event-stream/);assert.match(streamed.body,/event: tracking/);assert.equal((await get(`/v1/orders/${parcel.id}/tracking/stream`,'bob')).statusCode,404);
  await food.vendorAction(users.admin.id,next.id,'ready');await action(next.id,'picked_up','r2');await action(next.id,'on_the_way','r2');assert.equal((await action(next.id,'delivered','r2')).statusCode,200);assert.equal((await get('/v1/riders/me/job','r2')).json(),null);
  const unconfigured=await book('dispatch');await pay(unconfigured.id);await db.query('DELETE FROM vendo_internal.matching_policies WHERE city_id=$1',[cityId]);assert.equal((await matching.process(100)).no_rider,1);assert.equal((await track(unconfigured.id)).json().matching.reason,'matching_not_configured');assert.equal((await post(`/v1/orders/${unconfigured.id}/matching/cancel`)).statusCode,200);
  assert.equal((await review('r1','suspended')).statusCode,200);assert.equal((await locate()).statusCode,403);assert.equal((await online()).statusCode,403);assert.equal((await post('/v1/riders/register',{city_id:cityId,vehicle_type:'motorcycle',plate_number:'KD-R1'},'r1')).statusCode,403);
});
