import { docxFixture } from './docx-fixture.js';
import { docxMime, type ObjectStorage } from '../src/modules/media/schema.js';
import { PostgresMediaRepository } from '../src/modules/media/repository.js';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID, createHmac } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { PostgresMatchingRepository } from '../src/modules/matching/repository.js';
import { PostgresChatRepository } from '../src/modules/chat/repository.js';
import { PostgresOperationsRepository } from '../src/modules/operations/repository.js';
import { PostgresFinanceRepository } from '../src/modules/finance/repository.js';
import { FinanceService } from '../src/modules/finance/service.js';
import { PostgresPaymentRepository } from '../src/modules/payments/repository.js';
import { vendorInputSchema, menuInputSchema } from '../src/modules/food/schema.js';
import { financePolicy, type TransferGateway, type VerifiedTransfer } from '../src/modules/finance/schema.js';
import { bannerInput, tierInput } from '../src/modules/operations/schema.js';
import { fixtures, alice, bob } from './helpers.js';
test('Operations: private documents/chat, vendor scope, custody, growth, settlement and exact-once payouts', async (t) => {
    const db = new PGlite();
    t.after(() => db.close());
    await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;CREATE SCHEMA storage;CREATE TABLE storage.objects(id uuid DEFAULT gen_random_uuid(),bucket_id text);CREATE TABLE storage.buckets(id text PRIMARY KEY);ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;ALTER TABLE storage.buckets ENABLE ROW LEVEL SECURITY;GRANT USAGE ON SCHEMA storage TO anon,authenticated;GRANT ALL ON storage.objects,storage.buckets TO anon,authenticated;CREATE POLICY existing_open_objects ON storage.objects FOR ALL TO anon,authenticated USING(true) WITH CHECK(true);CREATE POLICY existing_open_buckets ON storage.buckets FOR ALL TO anon,authenticated USING(true) WITH CHECK(true);INSERT INTO storage.buckets VALUES('vendo-documents'),('vendo-public'),('unrelated');INSERT INTO storage.objects(bucket_id)VALUES('vendo-documents'),('vendo-public'),('unrelated');`);
    const dir = new URL('../supabase/migrations/', import.meta.url);
    for (const f of (await readdir(dir)).filter(n => n.endsWith('.sql')).sort())
        await db.exec(await readFile(new URL(f, dir), 'utf8'));
    const query = (sql: string, values?: unknown[]) => db.query(sql, values), pool = { query, connect: async () => ({ query, release() { } }) } as unknown as pg.Pool;
    const profiles = new PostgresProfileRepository(pool), food = new PostgresFoodRepository(pool), dispatch = new PostgresDispatchRepository(pool), matching = new PostgresMatchingRepository(pool), chat = new PostgresChatRepository(pool), operations = new PostgresOperationsRepository(pool, 'document-test-secret-with-at-least-32-characters'), finance = new PostgresFinanceRepository(pool), payments = new PostgresPaymentRepository(pool);
    const users = { alice, bob, admin: { id: randomUUID(), phone: '+2348011111111' }, staff: { id: randomUUID(), phone: '+2348022222222' }, r1: { id: randomUUID(), phone: '+2348033333333' }, r2: { id: randomUUID(), phone: '+2348044444444' } };
    for (const u of Object.values(users)) {
        await db.query('INSERT INTO auth.users(id) VALUES($1)', [u.id]);
        await profiles.bootstrap(u.id, u.phone);
        await profiles.setName(u.id, 'Test User');
        await profiles.setEmail(u.id, `${u.id}@example.com`);
    }
    await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [users.admin.id]);
    await db.query("UPDATE public.profiles SET role='vendor_staff' WHERE id=$1", [users.staff.id]);
    const city = (await db.query<{
        id: string;
    }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
    await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1', [city, JSON.stringify([{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }])]);
    const vendor = await food.saveVendor(users.admin.id, vendorInputSchema.parse({ name: 'Kitchen', category: 'restaurant', city_id: city, address: 'Pickup', location: { lat: 10.5, lng: 7.5 }, is_open: true })), menu = await food.saveMenu(users.admin.id, vendor.id, menuInputSchema.parse({ name: 'Rice', category: 'Meals', price_kobo: 250000 }));
    await food.assignStaff(users.admin.id, vendor.id, users.staff.id);
    await matching.savePolicy(users.admin.id, city, { initial_radius_m: 500, max_radius_m: 2000, radius_step_m: 500, expansion_seconds: 5, offer_seconds: 30, search_seconds: 60, location_max_age_seconds: 60, max_accuracy_m: 50 });
    const transfers = new Map<string, VerifiedTransfer>();
    let submissions = 0, failSubmit = false, failVerify = false;
    const gateway: TransferGateway = { configured: true, async resolve(i) { return { account_name: 'Verified Holder', account_number: i.account_number }; }, async recipient(i) { return i.account_number.endsWith('1111') ? 'RCP_riderone' : 'RCP_vendortwo'; }, async submit(i) {
            submissions++;
            transfers.set(i.reference, { reference: i.reference, amount: i.amount_kobo, currency: 'NGN', status: 'pending', domain: 'test', transfer_code: `TRF_${submissions}`, recipient_code: i.recipient_code });
            if (failSubmit)
                throw new Error('Timeout');
        }, async verify(ref) {
            if (failVerify)
                throw new Error('Unavailable');
            const v = transfers.get(ref);
            if (!v)
                throw new Error('Not found');
            return v;
        } };
    const files = new Map<string, Buffer>();
    const objects: ObjectStorage = { configured: true, async put(path, data) { files.set(path, data); }, async download(path) { return files.get(path)!; }, async signed(path) { return `https://storage.example.com/private/${path}?token=test`; }, publicUrl(path) { return `https://storage.example.com/public/${path}`; } };
    const media = new PostgresMediaRepository(pool, objects);
    const fx = fixtures();
    fx.dependencies.auth.authenticate = async (token) => {
        const u = users[token as keyof typeof users];
        if (!u)
            throw new Error('Invalid');
        return u;
    };
    const app = await buildApp(readEnv({ NODE_ENV: 'test', PAYSTACK_SECRET_KEY: 'sk_test_example' }), { ...fx.dependencies, profiles, food, dispatch, matching, chat, operations, finance, media, transferGateway: gateway, payments });
    t.after(() => app.close());
    const headers = (u = 'alice') => ({ authorization: `Bearer ${u}` }), get = (url: string, u = 'alice') => app.inject({ url, headers: headers(u) }), post = (url: string, payload: Record<string, unknown> = {}, u = 'alice', key?: string) => app.inject({ method: 'POST', url, headers: { ...headers(u), ...(key ? { 'idempotency-key': key } : {}) }, payload }), put = (url: string, payload: Record<string, unknown>, u = 'admin') => app.inject({ method: 'PUT', url, headers: headers(u), payload });
    assert.equal((await get('/v1/admin/orders')).statusCode, 403);
    assert.equal((await app.inject({ url: '/v1/admin/orders' })).statusCode, 401);
    for (const r of ['r1', 'r2'] as const)
        await matching.register(users[r].id, { city_id: city, vehicle_type: 'motorcycle', plate_number: `KD-${r}` });
    const pdf = Buffer.from('%PDF-1.7\nTest-only document.').toString('base64'), doc = await post('/v1/riders/me/documents', { kind: 'identity', mime: 'application/pdf', data_base64: pdf }, 'r1');
    assert.equal(doc.statusCode, 201, doc.body);
    assert.equal(doc.json().encrypted, undefined);
    await assert.rejects(() => matching.review(users.admin.id, users.r1.id, 'approved', 'Applicant reviewed.'), /Review all uploaded/);
    assert.equal((await get(`/v1/admin/rider-documents/${doc.json().id}/content`)).statusCode, 403);
    assert.equal((await get(`/v1/admin/rider-documents/${doc.json().id}/content`, 'admin')).json().data_base64, pdf);
    await operations.reviewDocument(users.admin.id, doc.json().id, 'approved', 'Identity manually verified.');
    assert.equal((await post('/v1/riders/me/documents', { kind: 'license', mime: 'image/png', data_base64: pdf }, 'r1')).statusCode, 400);
    for (const r of ['r1', 'r2'] as const) {
        await matching.review(users.admin.id, users[r].id, 'approved', 'Reviewed by operations.');
        await matching.locate(users[r].id, { lat: 10.5001, lng: 7.5, accuracy_m: 10, heading: null, speed_mps: null, captured_at: new Date().toISOString() });
        await matching.presence(users[r].id, true);
    }
    assert.equal((await get(`/v1/vendor/vendors/${vendor.id}/menu`, 'staff')).statusCode, 200);
    assert.equal((await get(`/v1/vendor/vendors/${vendor.id}/menu`, 'bob')).statusCode, 404);
    assert.equal((await put(`/v1/vendor/vendors/${vendor.id}/menu/${menu.id}`, { name: 'Rice', category: 'Meals', price_kobo: 250000, is_available: true }, 'staff')).statusCode, 200);
    const terms = financePolicy.parse({ enabled: true, vendor_commission_bps: 1000, rider_delivery_bps: 5000, rider_fixed_kobo: 1000, settlement_hold_hours: 1, minimum_withdrawal_kobo: 1000 });
    const policy = await finance.savePolicy(users.admin.id, city, terms);
    const quote = () => post('/v1/orders/quote', { type: 'food', vendor_id: vendor.id, items: [{ menu_item_id: menu.id, quantity: 1 }], dropoff: { lat: 10.6, lng: 7.6, address: 'Dropoff' } }), q = await quote();
    assert.equal(q.statusCode, 200, q.body);
    const booked = await post('/v1/orders', { quote_id: q.json().id, payment_method: 'wallet' }, 'alice', 'ops_booking_key');
    assert.equal(booked.statusCode, 201, booked.body);
    const order = booked.json();
    assert.equal((await post(`/v1/orders/${order.id}/chat/messages`, { text: 'Hello' }, 'alice', 'chat_before_assignment')).statusCode, 409);
    await db.query("UPDATE public.orders SET payment_status='paid',status='searching_rider' WHERE id=$1", [order.id]);
    const assigned = await post(`/v1/admin/orders/${order.id}/reassign`, { rider_id: users.r1.id, reason: 'Assign approved nearby rider.' }, 'admin');
    assert.equal(assigned.statusCode, 200, assigned.body);
    const send = (text: string, u = 'alice', key = 'chat_same_key') => post(`/v1/orders/${order.id}/chat/messages`, { text }, u, key), msg = await send('Please use the front gate.');
    assert.equal(msg.statusCode, 201, msg.body);
    assert.equal((await send('Please use the front gate.')).json().id, msg.json().id);
    assert.equal((await send('Different text')).statusCode, 409);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'bob')).statusCode, 404);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'admin')).statusCode, 404);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'r1')).json().unread, 1);
    await post(`/v1/orders/${order.id}/chat/read`, { seq: msg.json().seq }, 'r1');
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'r1')).json().unread, 0);
    assert.equal((await send('Approaching pickup.', 'r1', 'chat_rider_reply')).statusCode, 201);
    assert.equal((await post(`/v1/admin/orders/${order.id}/reassign`, { rider_id: users.r2.id, reason: 'First rider vehicle unavailable.' }, 'admin')).statusCode, 200);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'r2')).json().messages.length, 0);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'r1')).json().can_send, false);
    assert.equal((await send('Old rider blocked', 'r1', 'chat_old_rider_key')).statusCode, 409);
    assert.equal((await send('Hello replacement rider', 'alice', 'chat_replacement_key')).statusCode, 201);
    assert.equal((await get(`/v1/orders/${order.id}/chat`, 'r1')).json().messages.length, 2);
    await db.query("UPDATE public.orders SET status='picked_up',picked_up_at=now() WHERE id=$1", [order.id]);
    await assert.rejects(() => operations.reassign(users.admin.id, order.id, users.r1.id, 'Unsafe after pickup'), /before pickup/);
    await assert.rejects(() => operations.cancel(users.admin.id, order.id, 'Unsafe cancellation'), /custody/);
    await assert.rejects(() => operations.upload(users.r2.id, { kind: 'license', mime: 'application/pdf', data_base64: pdf }), /active delivery/);
    await db.query("UPDATE public.orders SET status='disputed' WHERE id=$1", [order.id]);
    await operations.custody(users.admin.id, order.id, 'delivered', 'Rider and customer both confirmed delivery.');
    assert.equal((await send('After delivery', 'alice', 'chat_after_delivery_key')).statusCode, 409);
    const stream = await get(`/v1/orders/${order.id}/chat/stream`);
    assert.equal(stream.statusCode, 200);
    assert.match(stream.body, /event: chat/);
    assert.match(stream.body, /Hello replacement rider/);
    await db.query("UPDATE public.orders SET delivered_at=now()-interval '2 hours' WHERE id=$1", [order.id]);
    await finance.savePolicy(users.admin.id, city, { ...terms, vendor_commission_bps: 5000 });
    assert.equal(await finance.settle(20), 1);
    assert.equal(await finance.settle(20), 0);
    assert.equal((await finance.account(users.r2.id, 'rider', users.r2.id)).available_kobo, 23500);
    assert.equal((await finance.account(users.staff.id, 'vendor', vendor.id)).available_kobo, 225000);
    assert.equal(Number((await db.query<{
        platform_kobo: string;
    }>('SELECT platform_kobo FROM vendo_internal.settlements WHERE order_id=$1', [order.id])).rows[0]!.platform_kobo), 46500);
    await assert.rejects(() => finance.account(bob.id, 'rider', users.r2.id), /not found/);
    await assert.rejects(() => finance.attachPolicy(users.admin.id, order.id, policy.id), /Settled/);
    const service = new FinanceService(finance, gateway, true);
    await service.bank(users.r2.id, 'rider', users.r2.id, { bank_code: '044', account_number: '0000001111' });
    await service.bank(users.staff.id, 'vendor', vendor.id, { bank_code: '044', account_number: '0000002222' });
    assert.equal((await get(`/v1/earnings/rider/${users.r2.id}/bank`, 'r2')).json().account_number, undefined);
    await assert.rejects(() => finance.withdraw(users.r2.id, 'rider', users.r2.id, 999, 'minimum_key'), /minimum/);
    const w = await finance.withdraw(users.r2.id, 'rider', users.r2.id, 10000, 'withdraw_same_key');
    assert.equal((await finance.withdraw(users.r2.id, 'rider', users.r2.id, 10000, 'withdraw_same_key')).id, w.id);
    assert.equal((await finance.account(users.r2.id, 'rider', users.r2.id)).held_kobo, 10000);
    await assert.rejects(() => finance.withdraw(users.r2.id, 'rider', users.r2.id, 20000, 'insufficient_key'), /Insufficient/);
    await assert.rejects(() => service.bank(users.r2.id, 'rider', users.r2.id, { bank_code: '044', account_number: '0000001111' }), /pending withdrawals/);
    await finance.review(users.admin.id, w.id, 'reject', 'Requested by rider for correction.');
    await finance.review(users.admin.id, w.id, 'reject', 'Retry rejection safely.');
    assert.equal((await finance.account(users.r2.id, 'rider', users.r2.id)).available_kobo, 23500);
    const approved = await finance.withdraw(users.r2.id, 'rider', users.r2.id, 10000, 'approved_withdraw_key');
    await finance.review(users.admin.id, approved.id, 'approve', 'Bank owner and earnings verified.');
    assert.equal((await new FinanceService(finance, gateway, false).process()).submitted, 0);
    assert.equal(submissions, 0);
    failSubmit = true;
    failVerify = true;
    assert.equal((await service.process()).review, 2);
    assert.equal(submissions, 1);
    failSubmit = false;
    failVerify = false;
    transfers.get(approved.reference)!.status = 'success';
    await service.process();
    await service.process();
    assert.equal(submissions, 1);
    assert.equal((await finance.account(users.r2.id, 'rider', users.r2.id)).held_kobo, 0);
    await db.query("UPDATE vendo_internal.withdrawals SET updated_at=now()-interval '40 days' WHERE id=$1", [approved.id]);
    const raw = JSON.stringify({ event: 'transfer.reversed', data: { reference: approved.reference, amount: 1 } }), hook = (signature = createHmac('sha512', 'sk_test_example').update(raw).digest('hex')) => app.inject({ method: 'POST', url: '/v1/hooks/paystack', headers: { 'content-type': 'application/json', 'x-paystack-signature': signature }, payload: raw });
    assert.equal((await hook('a'.repeat(128))).statusCode, 401);
    await hook();
    await hook();
    assert.equal((await db.query('SELECT * FROM vendo_internal.transfer_events')).rows.length, 1);
    transfers.get(approved.reference)!.status = 'reversed';
    await service.process();
    await service.process();
    assert.equal((await finance.account(users.r2.id, 'rider', users.r2.id)).available_kobo, 23500);
    const vw = await finance.withdraw(users.staff.id, 'vendor', vendor.id, 50000, 'vendor_withdraw_key');
    await finance.review(users.admin.id, vw.id, 'approve', 'Vendor banking and earnings verified.');
    await service.process();
    const correct = { ...transfers.get(vw.reference)! };
    await assert.rejects(() => finance.apply(vw.reference, { ...correct, amount: 1 }), /does not match/);
    assert.equal((await finance.account(users.staff.id, 'vendor', vendor.id)).held_kobo, 50000);
    transfers.get(vw.reference)!.status = 'failed';
    await service.process();
    await service.process();
    assert.equal((await finance.account(users.staff.id, 'vendor', vendor.id)).available_kobo, 225000);
    assert.match((await get(`/v1/earnings/vendor/${vendor.id}/export.csv`, 'staff')).body, /earning:vendor/);
    const image = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).toString('base64');
    const logo = await post('/v1/media', { purpose: 'logo', vendor_id: vendor.id, mime: 'image/png', data_base64: image }, 'staff');
    assert.equal(logo.statusCode, 201, logo.body);
    assert.match(logo.json().public_url, /public/);
    assert.equal((await get(`/v1/media/${logo.json().id}`, 'bob')).statusCode, 404);
    assert.equal((await post('/v1/media', { purpose: 'logo', mime: 'image/png', data_base64: image }, 'alice')).statusCode, 404);
    const privateDoc = await post('/v1/media', { purpose: 'document', mime: docxMime, data_base64: docxFixture().toString('base64') });
    assert.equal(privateDoc.statusCode, 201, privateDoc.body);
    assert.equal(privateDoc.json().public_url, null);
    assert.equal((await post(`/v1/media/${privateDoc.json().id}/download`, {}, 'bob')).statusCode, 404);
    assert.equal((await post(`/v1/media/${privateDoc.json().id}/download`)).json().expires_in, 60);
    const storedOps = new PostgresOperationsRepository(pool, undefined, objects), uploaded = await storedOps.upload(users.r1.id, { kind: 'license', mime: docxMime, data_base64: docxFixture().toString('base64') });
    assert.equal((await storedOps.document(users.admin.id, uploaded.id)).data_base64, docxFixture().toString('base64'));
    const source = (await db.query<{
        encrypted: string | null;
        storage_path: string | null;
    }>('SELECT encrypted,storage_path FROM vendo_internal.rider_documents WHERE id=$1', [uploaded.id])).rows[0]!;
    assert.equal(source.encrypted, null);
    assert.match(source.storage_path as string, /riders/);
    assert.equal((await operations.documents(users.admin.id, users.r1.id)).length, 2);
    assert.equal((await db.query('SELECT terms FROM vendo_internal.order_finance_terms WHERE order_id=$1', [order.id])).rows.length, 1);
    const dates = { starts_at: new Date(Date.now() - 60000).toISOString(), ends_at: new Date(Date.now() + 86400000).toISOString() }, tier = await operations.saveTier(users.admin.id, tierInput.parse({ name: 'Featured', active: true, placement_rank: 10, commission_bps: 1500 }));
    await operations.membership(users.admin.id, vendor.id, { tier_id: tier.id, ...dates });
    assert.equal((await operations.placements(city))[0]!.sponsored, true);
    await operations.saveBanner(users.admin.id, bannerInput.parse({ city_id: city, title: 'Test promotion', body: 'Configured campaign', image_url: null, action: 'vendor', vendor_id: vendor.id, active: true, priority: 10, ...dates }));
    assert.equal((await app.inject({ url: `/v1/growth/banners?city_id=${city}` })).json().length, 1);
    const stale = (await quote()).json();
    await operations.saveCity(users.admin.id, city, { is_active: true, base_fare_kobo: 30000, per_km_rate_kobo: 10000, minimum_delivery_fee_kobo: 0, minimum_food_subtotal_kobo: 0, opens_at: null, closes_at: null, surge_bps: 20000 });
    assert.equal((await post('/v1/orders', { quote_id: stale.id, payment_method: 'wallet' }, 'alice', 'surge_stale_quote')).statusCode, 409);
    const surged = (await quote()).json();
    assert.equal(surged.delivery_fee_kobo, 90000);
    assert.equal(surged.surge_bps, 20000);
    const report = await operations.report(users.admin.id, { from: new Date(Date.now() - 86400000).toISOString(), to: new Date(Date.now() + 60000).toISOString(), city_id: city });
    assert.equal(report[0]!.paid_orders, 1);
    assert.equal(report[0]!.paid_kobo, 295000);
    await operations.heartbeat('matching', true, 20);
    assert.equal((await operations.health(users.admin.id)).workers[0]!.kind, 'matching');
    assert.ok((await operations.audits(users.admin.id, 100, 0)).length > 0);
    await assert.rejects(() => new PostgresAccountRepository(pool).requestDeletion(users.r2.id, null), /earnings/);
    await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [users.r1.id]);
    await db.exec('SET ROLE authenticated');
    assert.equal((await db.query('SELECT * FROM public.order_messages')).rows.length, 2);
    assert.equal((await db.query('SELECT * FROM storage.objects')).rows.length, 1);
    assert.equal((await db.query('SELECT * FROM storage.buckets')).rows.length, 1);
    await assert.rejects(() => db.query("INSERT INTO storage.objects(bucket_id)VALUES('vendo-documents')"));
    await assert.rejects(() => db.query('SELECT * FROM vendo_internal.rider_documents'));
    await assert.rejects(() => db.query('SELECT * FROM vendo_internal.earnings_accounts'));
    await assert.rejects(() => db.query("UPDATE public.order_messages SET text='tampered'"));
    await db.exec('RESET ROLE');
    await assert.rejects(() => db.query('DELETE FROM vendo_internal.earnings_ledger'));
    await assert.rejects(() => db.query('DELETE FROM vendo_internal.settlements'));
});
