import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { menuInputSchema, vendorInputSchema } from '../src/modules/food/schema.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { packageConfigSchema } from '../src/modules/dispatch/schema.js';
import { PostgresOrderRepository } from '../src/modules/orders/repository.js';
import { transition, type TransitionRow } from '../src/modules/orders/transitions.js';
import { fixtures, alice, bob } from './helpers.js';

test('transition rules refuse unpaid fulfillment, skipped vendor confirmation and missing assignment', async () => {
  const client = { async query() { throw new Error('No write expected'); } } as unknown as pg.PoolClient;
  const row: TransitionRow = { id: randomUUID(), type:'food', status:'pending_payment', payment_status:'unpaid', quote:{ total_kobo:100000 } };
  await assert.rejects(() => transition(client,row,'awaiting_vendor',alice.id),/Verified payment/);
  await assert.rejects(() => transition(client,{...row,payment_status:'paid'},'searching_rider',alice.id),/not valid/);
  await assert.rejects(() => transition(client,{...row,payment_status:'paid',status:'scheduled',scheduled_at:new Date()},'searching_rider',alice.id),/not valid/);
  await assert.rejects(() => transition(client,{...row,status:'rider_assigned',payment_status:'paid'},'picked_up',alice.id),/assignment/);
  await assert.rejects(() => transition(client,{...row,status:'rider_assigned',payment_status:'paid',assigned_rider_id:bob.id},'picked_up',alice.id),/mark the order ready/);
});

test('Orders API/SQL: timelines, receipts, cancellation/refund intent, disputes, ratings, schedules and due-job retries', async (t) => {
  const db = new PGlite(); t.after(() => db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  const migrations = new URL('../supabase/migrations/',import.meta.url);
  for(const file of (await readdir(migrations)).filter((name)=>name.endsWith('.sql')).sort()) await db.exec(await readFile(new URL(file,migrations),'utf8'));
  const query = (sql:string,values?:unknown[])=>db.query(sql,values);
  const pool = { query, connect:async()=>({query,release(){}}) } as unknown as pg.Pool;
  const profiles = new PostgresProfileRepository(pool), food = new PostgresFoodRepository(pool), dispatch = new PostgresDispatchRepository(pool), orders = new PostgresOrderRepository(pool);
  const admin={id:randomUUID(),phone:'+2348011111111'},rider={id:randomUUID(),phone:'+2348022222222'};
  for(const user of [alice,bob,admin,rider]) { await db.query('INSERT INTO auth.users(id) VALUES($1)',[user.id]); await profiles.bootstrap(user.id,user.phone); await profiles.setName(user.id,'Test User'); await profiles.setEmail(user.id,`${user.id}@example.com`); }
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1",[admin.id]); await db.query("UPDATE public.profiles SET role='rider' WHERE id=$1",[rider.id]);
  const cityId=(await db.query<{id:string}>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
  await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1',[cityId,JSON.stringify([{lat:10,lng:7},{lat:11,lng:7},{lat:11,lng:8},{lat:10,lng:8}])]);
  const vendor=await food.saveVendor(admin.id,vendorInputSchema.parse({name:'Test kitchen',category:'restaurant',city_id:cityId,address:'Pickup',location:{lat:10.5,lng:7.5},is_open:true}));
  const menu=await food.saveMenu(admin.id,vendor.id,menuInputSchema.parse({name:'Rice',category:'Meals',price_kobo:250000}));
  await dispatch.savePackage(admin.id,cityId,packageConfigSchema.parse({size:'small',label:'Small',fee_kobo:10000,max_weight_g:5000,max_length_cm:40,max_width_cm:30,max_height_cm:30}));
  const fixture=fixtures(),authenticate=fixture.dependencies.auth.authenticate;
  fixture.dependencies.auth.authenticate=async(token)=>token==='admin'?admin:token==='rider'?rider:authenticate(token);
  const app=await buildApp(readEnv({NODE_ENV:'test',DISPATCH_DELIVERY_CODE_SECRET:'test-order-code-secret-at-least-32-chars'}),{...fixture.dependencies,profiles,food,dispatch,orders}); t.after(()=>app.close());
  const headers=(user='alice')=>({authorization:`Bearer ${user}`});
  const policy={assigned_cancellation_fee_kobo:10000,food_cancel_after_accept:false,schedule_min_lead_minutes:30,schedule_max_days:7,schedule_edit_cutoff_minutes:10,schedule_activation_lead_minutes:15,unpaid_timeout_minutes:10,vendor_timeout_minutes:5,dispute_window_hours:48};
  const savePolicy=(user='admin')=>app.inject({method:'PUT',url:`/v1/admin/cities/${cityId}/order-policy`,headers:headers(user),payload:policy});
  assert.equal((await savePolicy('alice')).statusCode,403);
  const foodInput={type:'food',vendor_id:vendor.id,items:[{menu_item_id:menu.id,quantity:1}],dropoff:{lat:10.6,lng:7.6,address:'Drop-off'}};
  const dispatchInput={type:'dispatch',city_id:cityId,pickup:{lat:10.5,lng:7.5,address:'Pickup'},dropoff:{lat:10.6,lng:7.6,address:'Drop-off'},package:{size:'small',description:'Shoes',fits_size:true,prohibited_items_acknowledged:true},receiver:{name:'Receiver',phone:bob.phone}};
  let sequence=0;
  const book=async(type='dispatch',scheduled_at?:string)=>{
    const quote=await app.inject({method:'POST',url:'/v1/orders/quote',headers:headers(),payload:type==='food'?foodInput:dispatchInput}); assert.equal(quote.statusCode,200,quote.body);
    const key=`order_test_${++sequence}`;
    const body={type,quote_id:quote.json().id,payment_method:'card',...(scheduled_at?{scheduled_at}:{})};
    const response=await app.inject({method:'POST',url:'/v1/orders',headers:{...headers(),'idempotency-key':key},payload:body}); return {response,body,key};
  };
  const future=new Date(Date.now()+2*3600000).toISOString();
  assert.equal((await book('dispatch',future)).response.statusCode,503);
  const configured=await savePolicy(); assert.equal(configured.statusCode,200,configured.body);
  assert.equal((await book('dispatch',new Date(Date.now()+60000).toISOString())).response.statusCode,400);
  const unpaid=(await book('food')).response; assert.equal(unpaid.statusCode,201,unpaid.body);
  const unpaidId=unpaid.json().id;
  const get=(id:string,suffix:string,user='alice')=>app.inject({url:`/v1/orders/${id}/${suffix}`,headers:headers(user)});
  const cancel=(id:string,accepted_fee_kobo=0)=>app.inject({method:'POST',url:`/v1/orders/${id}/cancel`,headers:headers(),payload:{reason:'No longer needed',accepted_fee_kobo}});
  assert.equal((await get(unpaidId,'timeline','bob')).statusCode,404);
  assert.equal((await get(unpaidId,'receipt')).statusCode,409);
  assert.equal((await get(unpaidId,'cancellation')).json().eligible,true);
  assert.equal((await cancel(unpaidId)).json().status,'cancelled'); await cancel(unpaidId);
  assert.equal((await get(unpaidId,'timeline')).json().items.length,2);
  assert.equal((await db.query('SELECT * FROM vendo_internal.order_refunds WHERE order_id=$1',[unpaidId])).rows.length,0);
  // Future verified-payment integration uses the same transition helper; no API payment bypass.
  const pay=async(id:string)=>{
    await db.exec('BEGIN');
    await db.query("UPDATE public.orders SET payment_status='paid' WHERE id=$1",[id]);
    const row=(await db.query<TransitionRow>('SELECT * FROM public.orders WHERE id=$1 FOR UPDATE',[id])).rows[0]!;
    await transition({query} as unknown as pg.PoolClient,row,row.scheduled_at?'scheduled':row.type==='food'?'awaiting_vendor':'searching_rider',alice.id,'payment_verified'); await db.exec('COMMIT');
  };
  const paid=(await book()).response.json(); await pay(paid.id);
  await db.query("UPDATE public.orders SET assigned_rider_id=$2,status='rider_assigned' WHERE id=$1",[paid.id,rider.id]);
  assert.equal((await get(paid.id,'cancellation')).json().fee_kobo,10000);
  assert.equal((await cancel(paid.id)).json().error.code,'CANCELLATION_FEE_CHANGED');
  const cancelled=await cancel(paid.id,10000); assert.equal(cancelled.statusCode,200,cancelled.body); assert.equal(cancelled.json().refund_status,'pending'); await cancel(paid.id,10000);
  const receipt=await get(paid.id,'receipt'); assert.equal(receipt.statusCode,200,receipt.body);
  assert.equal(receipt.json().refund.amount_kobo,paid.quote.total_kobo-10000); assert.equal(receipt.json().refund.status,'pending');
  assert.equal((await db.query('SELECT * FROM vendo_internal.order_refunds WHERE order_id=$1',[paid.id])).rows.length,1);
  const moving=(await book()).response.json(); await pay(moving.id); await db.query("UPDATE public.orders SET assigned_rider_id=$2,status='rider_assigned' WHERE id=$1",[moving.id,rider.id]);
  const action=(id:string,action:string,user='rider')=>app.inject({method:'POST',url:`/v1/rider/orders/${id}/status`,headers:headers(user),payload:{action}});
  assert.equal((await action(moving.id,'picked_up','alice')).statusCode,403);
  assert.equal((await action(moving.id,'picked_up')).statusCode,200); assert.equal((await cancel(moving.id)).statusCode,409);
  assert.equal((await action(moving.id,'on_the_way')).statusCode,200);
  assert.equal((await action(moving.id,'delivered')).json().error.code,'DELIVERY_CODE_REQUIRED');
  const disputeBody={category:'delivery',message:'The delivery has not arrived.'};
  const dispute=(id:string)=>app.inject({method:'POST',url:`/v1/orders/${id}/dispute`,headers:headers(),payload:disputeBody});
  const ticket=await dispute(moving.id); assert.equal(ticket.statusCode,200,ticket.body); assert.equal((await dispute(moving.id)).json().id,ticket.json().id);
  assert.equal((await action(moving.id,'on_the_way')).statusCode,409);
  const resolution={resolution:'Support reviewed the delivery issue.'};
  assert.equal((await app.inject({method:'POST',url:`/v1/admin/orders/${moving.id}/dispute/resolve`,headers:headers(),payload:resolution})).statusCode,403);
  assert.equal((await app.inject({method:'POST',url:`/v1/admin/orders/${moving.id}/dispute/resolve`,headers:headers('admin'),payload:resolution})).json().status,'resolved');
  // Trusted fixture recovery releases disputed custody before another job.
  await db.query('UPDATE public.orders SET assigned_rider_id=NULL WHERE id=$1',[moving.id]);
  const fulfilled=(await book('food')).response.json(); await pay(fulfilled.id); await food.vendorAction(admin.id,fulfilled.id,'accept');
  assert.equal((await get(fulfilled.id,'cancellation')).json().reason,'FOOD_ALREADY_ACCEPTED');
  await db.query("UPDATE public.orders SET assigned_rider_id=$2,status='rider_assigned' WHERE id=$1",[fulfilled.id,rider.id]);
  assert.equal((await action(fulfilled.id,'picked_up')).statusCode,409);
  await food.vendorAction(admin.id,fulfilled.id,'ready'); await action(fulfilled.id,'picked_up'); await action(fulfilled.id,'on_the_way');
  const delivered=await action(fulfilled.id,'delivered'); assert.equal(delivered.statusCode,200,delivered.body); assert.ok(delivered.json().delivered_at); await action(fulfilled.id,'delivered');
  const ratingBody={service_rating:5,vendor_rating:4,rider_rating:5,comment:'Great delivery'};
  const rate=(id:string,payload=ratingBody,user='alice')=>app.inject({method:'POST',url:`/v1/orders/${id}/rating`,headers:headers(user),payload});
  assert.equal((await rate(fulfilled.id,ratingBody,'bob')).statusCode,404);
  assert.equal((await rate(moving.id)).statusCode,409);
  const rated=await rate(fulfilled.id); assert.equal(rated.statusCode,200,rated.body); assert.equal((await rate(fulfilled.id)).json().id,rated.json().id);
  assert.equal((await rate(fulfilled.id,{...ratingBody,vendor_rating:2})).statusCode,409);
  assert.equal((await food.getVendor(vendor.id))!.vendor.rating,4);
  const scheduledBooking=await book('dispatch',future); assert.equal(scheduledBooking.response.statusCode,201,scheduledBooking.response.body);
  const scheduled=scheduledBooking.response.json();
  const shifted=new Date(Date.now()+3*3600000).toISOString();
  const rescheduled=await app.inject({method:'PATCH',url:`/v1/orders/${scheduled.id}/schedule`,headers:headers(),payload:{scheduled_at:shifted}}); assert.equal(rescheduled.statusCode,200,rescheduled.body);
  const retry=await app.inject({method:'POST',url:'/v1/orders',headers:{...headers(),'idempotency-key':scheduledBooking.key},payload:scheduledBooking.body}); assert.equal(retry.json().id,scheduled.id);
  await orders.processDue(100); assert.equal((await db.query<{status:string}>('SELECT status FROM public.orders WHERE id=$1',[scheduled.id])).rows[0]!.status,'pending_payment');
  await pay(scheduled.id); await db.query("UPDATE public.orders SET processing_due_at=now()-interval '1 minute' WHERE id=$1",[scheduled.id]);
  assert.equal((await orders.processDue(100)).activated,1); assert.equal((await orders.processDue(100)).activated,0);
  const scheduledFood=(await book('food',future)).response.json(); await pay(scheduledFood.id);
  await db.query("UPDATE public.orders SET scheduled_at=now()+interval '5 minutes' WHERE id=$1",[scheduledFood.id]);
  assert.equal((await cancel(scheduledFood.id)).json().error.code,'SCHEDULE_CUTOFF_REACHED');
  assert.equal((await app.inject({method:'PATCH',url:`/v1/orders/${scheduledFood.id}/schedule`,headers:headers(),payload:{scheduled_at:shifted}})).statusCode,409);
  await db.query("UPDATE public.orders SET processing_due_at=now()-interval '1 minute' WHERE id=$1",[scheduledFood.id]);
  await orders.processDue(100); assert.equal((await db.query<{status:string}>('SELECT status FROM public.orders WHERE id=$1',[scheduledFood.id])).rows[0]!.status,'awaiting_vendor');
  await db.query("UPDATE public.orders SET status_updated_at=now()-interval '10 minutes' WHERE id=$1",[scheduledFood.id]);
  assert.equal((await orders.processDue(100)).cancelled,1); assert.equal((await get(scheduledFood.id,'receipt')).json().refund.amount_kobo,scheduledFood.quote.total_kobo);
  const expire=(await book()).response.json(); await db.query("UPDATE public.orders SET created_at=now()-interval '20 minutes' WHERE id=$1",[expire.id]);
  assert.equal((await orders.processDue(100)).expired,1); assert.equal((await orders.processDue(100)).expired,0);
  await db.query("UPDATE public.orders SET cancelled_at=now()-interval '49 hours' WHERE id=$1",[paid.id]);
  assert.equal((await dispute(paid.id)).json().error.code,'DISPUTE_WINDOW_CLOSED');
  const unavailable=(await book('food',future)).response.json(); await pay(unavailable.id); await db.query("UPDATE public.orders SET processing_due_at=now()-interval '1 minute' WHERE id=$1",[unavailable.id]); await db.query('UPDATE public.vendors SET is_open=false WHERE id=$1',[vendor.id]);
  assert.equal((await orders.processDue(100)).cancelled,1);
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[bob.id]); await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.order_ratings')).rows.length,0); assert.equal((await db.query('SELECT * FROM public.order_disputes')).rows.length,0);
  await assert.rejects(()=>db.query('SELECT * FROM vendo_internal.order_refunds')); await assert.rejects(()=>db.query('DELETE FROM public.order_ratings')); await db.exec('RESET ROLE');
});
