import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile,readdir } from 'node:fs/promises';
import { createHmac,randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresDispatchRepository } from '../src/modules/dispatch/repository.js';
import { packageConfigSchema } from '../src/modules/dispatch/schema.js';
import { PostgresOrderRepository } from '../src/modules/orders/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { PostgresPaymentRepository } from '../src/modules/payments/repository.js';
import { PaymentService } from '../src/modules/payments/service.js';
import { menuInputSchema,vendorInputSchema } from '../src/modules/food/schema.js';
import { channels,type Intent,type PaymentGateway,type VerifiedRefund,type VerifiedTransaction } from '../src/modules/payments/schema.js';
import { fixtures,alice,bob } from './helpers.js';

test('Payments API/SQL: fixed amounts, signed durable hooks, exact-once credits/debits/refunds, reconciliation and late success',async(t)=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
  const dir=new URL('../supabase/migrations/',import.meta.url);
  for(const file of (await readdir(dir)).filter(name=>name.endsWith('.sql')).sort())await db.exec(await readFile(new URL(file,dir),'utf8'));
  const query=(sql:string,values?:unknown[])=>db.query(sql,values),pool={query,connect:async()=>({query,release(){}})} as unknown as pg.Pool;
  const profiles=new PostgresProfileRepository(pool),food=new PostgresFoodRepository(pool),orders=new PostgresOrderRepository(pool),payments=new PostgresPaymentRepository(pool),accounts=new PostgresAccountRepository(pool),dispatch=new PostgresDispatchRepository(pool);
  const admin={id:randomUUID(),phone:'+2348011111111'};
  for(const user of [alice,bob,admin]){await db.query('INSERT INTO auth.users(id) VALUES($1)',[user.id]);await profiles.bootstrap(user.id,user.phone);await profiles.setName(user.id,'Test');await profiles.setEmail(user.id,`${user.id}@example.com`);}
  await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1",[admin.id]);
  const cityId=(await db.query<{id:string}>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
  await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1',[cityId,JSON.stringify([{lat:10,lng:7},{lat:11,lng:7},{lat:11,lng:8},{lat:10,lng:8}])]);
  const vendor=await food.saveVendor(admin.id,vendorInputSchema.parse({name:'Kitchen',category:'restaurant',city_id:cityId,address:'Pickup',location:{lat:10.5,lng:7.5},is_open:true}));
  const menu=await food.saveMenu(admin.id,vendor.id,menuInputSchema.parse({name:'Rice',category:'Meals',price_kobo:250000}));
  await dispatch.savePackage(admin.id,cityId,packageConfigSchema.parse({size:'small',label:'Small',fee_kobo:10000,max_weight_g:5000,max_length_cm:40,max_width_cm:30,max_height_cm:30}));
  const initialized=new Map<string,Intent>(),transactions=new Map<string,VerifiedTransaction>();let initializeCalls=0,failInit=false,failVerify=false;
  const gateway:PaymentGateway={async verifyRefund(){throw new Error('Unused');},async initialize(intent){initializeCalls++;initialized.set(intent.reference,intent);if(failInit)throw new Error('Timeout');return {reference:intent.reference,authorization_url:'https://checkout.paystack.com/test',access_code:'test_access'};},async verify(ref){if(failVerify)throw new Error('Offline');const value=transactions.get(ref);if(!value)throw new Error('Not yet paid');return value;}};
  const refunds=new Map<string,VerifiedRefund>();
  gateway.verifyRefund=async(id)=>{const refund=refunds.get(id);if(!refund)throw new Error('Unknown refund');return refund;};
  const service=new PaymentService(payments,gateway),secret='sk_test_example';
  const fixture=fixtures(),authenticate=fixture.dependencies.auth.authenticate;fixture.dependencies.auth.authenticate=async(token)=>token==='admin'?admin:authenticate(token);
  const app=await buildApp(readEnv({NODE_ENV:'test',PAYSTACK_SECRET_KEY:secret,DISPATCH_DELIVERY_CODE_SECRET:'payment-test-delivery-secret-at-least-32-characters'}),{...fixture.dependencies,profiles,food,orders,accounts,dispatch,payments,paymentGateway:gateway});t.after(()=>app.close());
  const headers=(user='alice')=>({authorization:`Bearer ${user}`});let sequence=0;
  const topup=(amount_kobo:number,key=`topup_test_${++sequence}`,method='card')=>app.inject({method:'POST',url:'/v1/wallet/top-ups',headers:{...headers(),'idempotency-key':key},payload:{amount_kobo,method}});
  const verify=(ref:string,user='alice')=>app.inject({method:'POST',url:`/v1/payments/${ref}/verify`,headers:headers(user)});
  const success=(ref:string,overrides:Partial<VerifiedTransaction>={})=>{
    const saved=initialized.get(ref)!;
    transactions.set(ref,{id:String(++sequence),reference:ref,status:'success',amount:saved.amount_kobo,currency:'NGN',domain:'test',channel:channels[saved.method],customer:{email:saved.email},metadata:{payment_id:saved.id,customer_id:saved.customer_id,order_id:saved.order_id,purpose:saved.purpose},...overrides});
  };
  const balance=async(user='alice')=>(await app.inject({url:'/v1/wallet',headers:headers(user)})).json().balance_kobo as number;
  const book=async(method='wallet',scheduled_at?:string)=>{
    const quote=await app.inject({method:'POST',url:'/v1/orders/quote',headers:headers(),payload:{type:'food',vendor_id:vendor.id,items:[{menu_item_id:menu.id,quantity:1}],dropoff:{lat:10.6,lng:7.6,address:'Dropoff'}}});assert.equal(quote.statusCode,200,quote.body);
    const order=await app.inject({method:'POST',url:'/v1/orders',headers:{...headers(),'idempotency-key':`booking_test_${++sequence}`},payload:{quote_id:quote.json().id,payment_method:method,...(scheduled_at?{scheduled_at}:{})}});assert.equal(order.statusCode,201,order.body);return order.json();
  };
  const initialize=(orderId:string,key=`payment_test_${++sequence}`)=>app.inject({method:'POST',url:'/v1/payments/orders',headers:{...headers(),'idempotency-key':key},payload:{order_id:orderId}});
  const payWallet=(id:string,user='alice')=>app.inject({method:'POST',url:`/v1/orders/${id}/pay/wallet`,headers:headers(user)});
  assert.equal((await app.inject({url:'/v1/wallet'})).statusCode,401);
  await db.query('UPDATE public.profiles SET email=NULL WHERE id=$1',[bob.id]);assert.equal((await app.inject({url:'/v1/wallet',headers:headers('bob')})).statusCode,403);await profiles.setEmail(bob.id,`${bob.id}@example.com`);
  assert.equal(await balance(),0);
  const unpaid=await book();assert.equal((await payWallet(unpaid.id)).json().error.code,'INSUFFICIENT_FUNDS');assert.equal(await balance(),0);
  assert.equal((await payWallet(unpaid.id,'bob')).statusCode,404);
  assert.equal((await initialize(unpaid.id)).statusCode,409);
  const start=await topup(1000000,'topup_same_key');assert.equal(start.statusCode,200,start.body);const top=start.json();
  assert.equal(top.status,'pending');assert.equal(top.email,undefined);assert.equal(top.customer_id,undefined);
  assert.equal((await topup(1000000,'topup_same_key')).json().id,top.id);assert.equal(initializeCalls,1);
  assert.equal((await topup(1000001,'topup_same_key')).statusCode,409);
  assert.equal((await verify(top.reference,'bob')).statusCode,404);
  await assert.rejects(()=>accounts.requestDeletion(alice.id,null),/active orders/);
  success(top.reference);
  const raw=JSON.stringify({event:'charge.success',data:{reference:top.reference,amount:1,authorization:{authorization_code:'do-not-store'}}});
  const hook=(signature=createHmac('sha512',secret).update(raw).digest('hex'))=>app.inject({method:'POST',url:'/v1/hooks/paystack',headers:{'content-type':'application/json','x-paystack-signature':signature},payload:raw});
  assert.equal((await hook('a'.repeat(128))).statusCode,401);assert.equal(await balance(),0);
  assert.equal((await hook()).statusCode,200);assert.equal((await hook()).statusCode,200);assert.equal(await balance(),0);
  assert.equal((await db.query('SELECT * FROM vendo_internal.payment_webhooks')).rows.length,1);
  assert.equal((await service.process()).verified,1);assert.equal(await balance(),1000000);
  await verify(top.reference);await hook();await service.process();assert.equal(await balance(),1000000);
  const paid=await payWallet(unpaid.id);assert.equal(paid.statusCode,200,paid.body);assert.equal(paid.json().status,'awaiting_vendor');
  assert.equal(await balance(),1000000-unpaid.quote.total_kobo);await payWallet(unpaid.id);assert.equal(await balance(),1000000-unpaid.quote.total_kobo);
  const history=await app.inject({url:'/v1/wallet/transactions',headers:headers()});assert.equal(history.json().items.length,2);
  assert.equal((await app.inject({url:'/v1/wallet/transactions',headers:headers('bob')})).json().items.length,0);
  const cancel=await app.inject({method:'POST',url:`/v1/orders/${unpaid.id}/cancel`,headers:headers(),payload:{reason:'No longer needed'}});assert.equal(cancel.statusCode,200,cancel.body);assert.equal(cancel.json().refund_status,'pending');
  assert.equal((await service.process()).wallet_refunds,1);assert.equal((await service.process()).wallet_refunds,0);assert.equal(await balance(),1000000);
  const receipt=await app.inject({url:`/v1/orders/${unpaid.id}/receipt`,headers:headers()});assert.equal(receipt.statusCode,200,receipt.body);assert.equal(receipt.json().refund.status,'processed');assert.equal(receipt.json().order.refund_status,'refunded');
  assert.equal((await payWallet(unpaid.id)).json().status,'cancelled');assert.equal(await balance(),1000000);
  for(const method of ['card','transfer','ussd']){
    const order=await book(method);const init=await initialize(order.id);assert.equal(init.statusCode,200,init.body);const payment=init.json();assert.equal(payment.amount_kobo,order.quote.total_kobo);assert.equal(payment.method,method);
    assert.equal((await initialize(order.id)).json().id,payment.id);success(payment.reference);
    if(method==='card'){
      const actual=transactions.get(payment.reference)!;
      for(const wrong of [{currency:'USD'},{channel:'ussd'},{customer:{email:'wrong@example.com'}},{metadata:{...actual.metadata,customer_id:bob.id}},{reference:'unrelated'}]){transactions.set(payment.reference,{...actual,...wrong});assert.equal((await verify(payment.reference)).json().status,'review');assert.equal((await food.getOrder(alice.id,order.id))!.payment_status,'unpaid');}
      transactions.set(payment.reference,{...actual,amount:actual.amount-1});assert.equal((await verify(payment.reference)).json().status,'review');assert.equal((await food.getOrder(alice.id,order.id))!.payment_status,'unpaid');transactions.set(payment.reference,actual);
    }
    const verified=await verify(payment.reference);assert.equal(verified.statusCode,200,verified.body);assert.equal(verified.json().status,'succeeded');await verify(payment.reference);
    assert.equal((await food.getOrder(alice.id,order.id))!.status,'awaiting_vendor');assert.equal((await payWallet(order.id)).statusCode,409);
  }
  const late=await book('transfer');const latePayment=(await initialize(late.id)).json();
  await app.inject({method:'POST',url:`/v1/orders/${late.id}/cancel`,headers:headers(),payload:{reason:'Changed my mind'}});success(latePayment.reference);await verify(latePayment.reference);
  const lateOrder=await food.getOrder(alice.id,late.id);assert.equal(lateOrder!.status,'cancelled');assert.equal(lateOrder!.payment_status,'paid');assert.equal(lateOrder!.refund_status,'pending');
  assert.equal(Number((await db.query<{amount_kobo:string}>('SELECT amount_kobo FROM vendo_internal.order_refunds WHERE order_id=$1',[late.id])).rows[0]!.amount_kobo),late.quote.total_kobo);
  const refundId=(await db.query<{id:string}>('SELECT id FROM vendo_internal.order_refunds WHERE order_id=$1',[late.id])).rows[0]!.id;
  const providerTransaction=transactions.get(latePayment.reference)!.id;
  refunds.set('10001',{id:'10001',transaction:providerTransaction,amount:late.quote.total_kobo,currency:'NGN',domain:'test',status:'pending'});
  const reconcile=(user='admin')=>app.inject({method:'POST',url:`/v1/admin/refunds/${refundId}/reconcile`,headers:headers(user),payload:{provider_refund_id:'10001'}});
  assert.equal((await reconcile('alice')).statusCode,403);assert.equal((await reconcile()).json().status,'pending');
  refunds.get('10001')!.amount--;assert.equal((await reconcile()).statusCode,409);refunds.get('10001')!.amount++;refunds.get('10001')!.status='processed';
  assert.equal((await reconcile()).json().status,'processed');assert.equal((await reconcile()).json().status,'processed');assert.equal((await food.getOrder(alice.id,late.id))!.refund_status,'refunded');
  failInit=true;const before=initializeCalls;const timeout=await topup(1000,'timeout_same_key');assert.equal(timeout.statusCode,500);failInit=false;
  const retry=(await topup(1000,'timeout_same_key')).json();assert.equal(retry.status,'review');assert.equal(initializeCalls,before+1);success(retry.reference);await verify(retry.reference);assert.equal(await balance(),1001000);
  const recovery=(await topup(5000)).json();success(recovery.reference);failVerify=true;assert.equal((await verify(recovery.reference)).statusCode,500);assert.equal(await balance(),1001000);failVerify=false;await verify(recovery.reference);assert.equal(await balance(),1006000);
  const lost=(await topup(7000)).json();success(lost.reference);assert.equal((await service.process()).verified,1);assert.equal(await balance(),1013000);
  const beforeAtomic=await balance();const atomic=await book();
  await db.exec(`CREATE FUNCTION public.fail_payment_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.reason='wallet_payment' THEN RAISE EXCEPTION 'Test transaction rollback'; END IF; RETURN NEW; END; $$;
    CREATE TRIGGER test_payment_failure BEFORE INSERT ON public.order_events FOR EACH ROW EXECUTE FUNCTION public.fail_payment_event();`);
  assert.equal((await payWallet(atomic.id)).statusCode,500);assert.equal(await balance(),beforeAtomic);assert.equal((await food.getOrder(alice.id,atomic.id))!.payment_status,'unpaid');
  await db.exec('DROP TRIGGER test_payment_failure ON public.order_events; DROP FUNCTION public.fail_payment_event()');assert.equal((await payWallet(atomic.id)).statusCode,200);
  await orders.savePolicy(admin.id,cityId,{assigned_cancellation_fee_kobo:10000,food_cancel_after_accept:false,schedule_min_lead_minutes:30,schedule_max_days:7,schedule_edit_cutoff_minutes:10,schedule_activation_lead_minutes:15,unpaid_timeout_minutes:10,vendor_timeout_minutes:5,dispute_window_hours:48});
  const scheduled=await book('card',new Date(Date.now()+2*3600000).toISOString()),scheduledPayment=(await initialize(scheduled.id)).json();
  success(scheduledPayment.reference);await service.verify(scheduledPayment.reference,alice.id);assert.equal((await food.getOrder(alice.id,scheduled.id))!.status,'scheduled');
  const expired=await book('card'),expiredPayment=(await initialize(expired.id)).json();await db.query("UPDATE public.orders SET created_at=now()-interval '20 minutes' WHERE id=$1",[expired.id]);
  success(expiredPayment.reference);await service.verify(expiredPayment.reference,alice.id);assert.equal((await food.getOrder(alice.id,expired.id))!.status,'cancelled');assert.equal((await food.getOrder(alice.id,expired.id))!.refund_status,'pending');
  const dispatchQuote=await app.inject({method:'POST',url:'/v1/orders/quote',headers:headers(),payload:{type:'dispatch',city_id:cityId,pickup:{lat:10.5,lng:7.5,address:'Pickup'},dropoff:{lat:10.6,lng:7.6,address:'Dropoff'},package:{size:'small',description:'Shoes',fits_size:true,prohibited_items_acknowledged:true},receiver:{name:'Receiver',phone:bob.phone}}});assert.equal(dispatchQuote.statusCode,200,dispatchQuote.body);
  const dispatched=await app.inject({method:'POST',url:'/v1/orders',headers:{...headers(),'idempotency-key':'dispatch_payment_test'},payload:{type:'dispatch',quote_id:dispatchQuote.json().id,payment_method:'ussd'}});assert.equal(dispatched.statusCode,201,dispatched.body);
  const dispatchPayment=(await initialize(dispatched.json().id)).json();success(dispatchPayment.reference);await service.verify(dispatchPayment.reference,alice.id);assert.equal((await food.getOrder(alice.id,dispatched.json().id))!.status,'searching_rider');
  const blocked=await book();const balanceBeforeClosed=await balance();await db.query('UPDATE public.vendors SET is_open=false WHERE id=$1',[vendor.id]);assert.equal((await payWallet(blocked.id)).statusCode,409);assert.equal(await balance(),balanceBeforeClosed);await db.query('UPDATE public.vendors SET is_open=true WHERE id=$1',[vendor.id]);
  // Ledger can't be altered, including by trusted DB code; own reads are RLS-only.
  await assert.rejects(()=>db.query('UPDATE public.wallet_transactions SET amount_kobo=1'));
  await assert.rejects(()=>db.query('DELETE FROM public.wallet_transactions'));
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[bob.id]);await db.exec('SET ROLE authenticated');
  assert.equal((await db.query('SELECT * FROM public.wallet_transactions')).rows.length,0);await assert.rejects(()=>db.query('SELECT * FROM vendo_internal.payment_intents'));await assert.rejects(()=>db.query('UPDATE public.wallets SET balance_kobo=100'));await db.exec('RESET ROLE');
  // The database profile lock also guards deletion against unresolved money.
  await db.query('INSERT INTO public.wallets(customer_id,balance_kobo) VALUES($1,1000)',[bob.id]);
  await assert.rejects(()=>accounts.requestDeletion(bob.id,null),/unsettled payments/);
  await db.query('UPDATE public.wallets SET balance_kobo=0 WHERE customer_id=$1',[bob.id]);
  const bobIntent=(await payments.prepare(bob.id,'bob_pending_key',{amount_kobo:1000,method:'card'})).intent;
  await assert.rejects(()=>accounts.requestDeletion(bob.id,null),/unsettled payments/);
  await payments.initialized(bobIntent.id,{reference:bobIntent.reference,authorization_url:'https://checkout.paystack.com/test',access_code:'code'});
});
