import assert from 'node:assert/strict';
import { test } from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import type pg from 'pg';
import { buildApp } from '../src/app.js';
import { readEnv } from '../src/config/env.js';
import { PostgresProfileRepository } from '../src/modules/users/repository.js';
import { PostgresAccountRepository } from '../src/modules/accounts/repository.js';
import { PostgresVendorRepository } from '../src/modules/vendors/repository.js';
import { PostgresFoodRepository } from '../src/modules/food/repository.js';
import { PostgresOperationsRepository } from '../src/modules/operations/repository.js';
import { PostgresNotificationRepository } from '../src/modules/notifications/repository.js';
import { PostgresMediaRepository } from '../src/modules/media/repository.js';
import { registrationInput, storePatch } from '../src/modules/vendors/schema.js';
import { menuInputSchema } from '../src/modules/food/schema.js';
import type { ObjectStorage } from '../src/modules/media/schema.js';
import { fixtures, alice, bob } from './helpers.js';
test('Vendor registration: private applications, retry-safe review, role linking and scoped webapp store/menu/orders/media', async (t) => {
    const db = new PGlite();
    t.after(() => db.close());
    await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;GRANT USAGE ON SCHEMA public,auth TO anon,authenticated,service_role;GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated;`);
    const dir = new URL('../supabase/migrations/', import.meta.url);
    for (const file of (await readdir(dir)).filter(f => f.endsWith('.sql')).sort())
        await db.exec(await readFile(new URL(file, dir), 'utf8'));
    const query = (sql: string, args?: unknown[]) => db.query(sql, args), pool = { query, connect: async () => ({ query, release() { } }) } as unknown as pg.Pool, profiles = new PostgresProfileRepository(pool), vendors = new PostgresVendorRepository(pool), food = new PostgresFoodRepository(pool), operations = new PostgresOperationsRepository(pool), accounts = new PostgresAccountRepository(pool);
    const users = { alice, bob, admin: { id: randomUUID(), phone: '+2348011111111' }, rider: { id: randomUUID(), phone: '+2348022222222' }, incomplete: { id: randomUUID(), phone: '+2348033333333' } };
    for (const [key, u] of Object.entries(users)) {
        await db.query('INSERT INTO auth.users(id)VALUES($1)', [u.id]);
        await profiles.bootstrap(u.id, u.phone);
        if (key !== 'incomplete') {
            await profiles.setName(u.id, 'Test User');
            await profiles.setEmail(u.id, `${u.id}@example.com`);
        }
    }
    await db.query("UPDATE public.profiles SET role='admin' WHERE id=$1", [users.admin.id]);
    await db.query("UPDATE public.profiles SET role='rider' WHERE id=$1", [users.rider.id]);
    const city = (await db.query<{
        id: string;
    }>("SELECT id FROM public.cities WHERE name='Kaduna'")).rows[0]!.id;
    await db.query('UPDATE public.cities SET is_active=true,base_fare_kobo=30000,per_km_rate_kobo=10000,service_polygon=$2 WHERE id=$1', [city, JSON.stringify([{ lat: 10, lng: 7 }, { lat: 11, lng: 7 }, { lat: 11, lng: 8 }, { lat: 10, lng: 8 }])]);
    await db.query('INSERT INTO vendo_internal.city_order_policies VALUES($1,10000,false,30,7,10,15,10,5,48)',[city]);
    const storage: ObjectStorage = { configured: true, async put() { }, async download() { return Buffer.from('test'); }, async signed() { return 'https://example.com/private?token=short'; }, publicUrl(path) { return `https://example.com/public/${path}`; } };
    const notifications = new PostgresNotificationRepository(pool), media = new PostgresMediaRepository(pool, storage), fx = fixtures();
    fx.dependencies.auth.authenticate = async (token) => {
        const u = users[token as keyof typeof users];
        if (!u)
            throw new Error('Invalid');
        return u;
    };
    const app = await buildApp(readEnv({ NODE_ENV: 'test', CORS_ORIGINS: 'https://vendors.example.com' }), { ...fx.dependencies, profiles, vendors, food, operations, media, notifications });
    t.after(() => app.close());
    let requestNumber = 0;
    const h = (u = 'alice') => ({ authorization: `Bearer ${u}` }), get = (url: string, u = 'alice') => app.inject({ url, headers: h(u) }), post = (url: string, payload: Record<string, unknown> = {}, u = 'alice', key?: string) => app.inject({ method: 'POST', url, remoteAddress: `192.0.2.${++requestNumber}`, headers: { ...h(u), ...(key ? { 'idempotency-key': key } : {}) }, payload }), patch = (url: string, payload: Record<string, unknown>, u = 'alice') => app.inject({ method: 'PATCH', url, headers: h(u), payload });
    const input = registrationInput.parse({ name: 'New Kitchen', category: 'restaurant', cuisine: 'Local', description: 'Fresh meals', city_id: city, address: 'Shop 12 Market Road', location: { lat: 10.5, lng: 7.5 } }), submit = (data: Record<string, unknown> = input, u = 'alice', key = 'vendor_registration_key') => post('/v1/vendor/registration', data, u, key);
    assert.equal((await app.inject({ method: 'POST', url: '/v1/vendor/registration', headers: { 'idempotency-key': 'anonymous_key' }, payload: input })).statusCode, 401);
    assert.equal((await submit(input, 'incomplete')).statusCode, 403);
    assert.equal((await submit(input, 'rider')).statusCode, 403);
    assert.equal((await submit({ ...input, is_active: true })).statusCode, 400);
    assert.equal((await submit({ ...input, location: { lat: 9, lng: 7 } })).statusCode, 400);
    const file = await media.upload(bob.id, { purpose: 'document', mime: 'application/pdf', data_base64: Buffer.from('%PDF-test').toString('base64') });
    assert.equal((await submit({ ...input, document_ids: [file.id] })).statusCode, 404);
    const first = await submit();
    assert.equal(first.statusCode, 201, first.body);
    assert.equal(first.json().status, 'pending');
    assert.equal((await get('/v1/vendor/registration')).json().id, first.json().id);
    assert.equal((await submit()).json().id, first.json().id);
    assert.equal((await submit({ ...input, name: 'Changed' })).statusCode, 409);
    assert.equal((await submit(input, 'alice', 'second_pending_key')).statusCode, 409);
    assert.equal((await get('/v1/vendor/stores')).statusCode, 403);
    assert.equal((await get('/v1/vendor/registrations', 'bob')).json().length, 0);
    assert.equal((await get('/v1/admin/vendor-applications')).statusCode, 403);
    await assert.rejects(() => accounts.requestDeletion(alice.id, null), /vendor application/);
    const review = (id: string, decision = 'approve', u = 'admin') => post(`/v1/admin/vendor-applications/${id}/review`, { decision, note: 'Business and location manually checked.' }, u);
    assert.equal((await review(first.json().id, 'approve', 'bob')).statusCode, 403);
    const approved = await review(first.json().id);
    assert.equal(approved.statusCode, 200, approved.body);
    const id = approved.json().vendor_id as string;
    assert.equal((await review(first.json().id)).json().vendor_id, id);
    assert.equal((await review(first.json().id, 'reject')).statusCode, 409);
    assert.equal((await profiles.bootstrap(alice.id, alice.phone)).role, 'vendor_staff');
    const stores = await get('/v1/vendor/stores');
    assert.equal(stores.json().length, 1);
    assert.equal(stores.json()[0].is_open, false);
    assert.equal(stores.json()[0].description, 'Fresh meals');
    await assert.rejects(() => accounts.requestDeletion(alice.id, null), /handover/);
    assert.equal((await get(`/v1/vendor/stores/${id}`, 'bob')).statusCode, 404);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { is_active: true })).statusCode, 400);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, {})).statusCode, 400);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { name: 'Renamed' })).statusCode, 200);
    assert.equal((await get(`/v1/vendor/stores/${id}`)).json().cuisine, 'Local');
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { address: 'Elsewhere' })).statusCode, 400);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { address: 'Outside city', location: { lat: 9, lng: 7 } })).statusCode, 400);
    assert.equal(storePatch.safeParse({}).success, false);
    const added = await post(`/v1/vendor/stores/${id}/menu`, menuInputSchema.parse({ name: 'Rice', category: 'Meals', price_kobo: 250000 }));
    assert.equal(added.statusCode, 201, added.body);
    assert.equal((await get(`/v1/vendor/stores/${id}/menu`, 'bob')).statusCode, 404);
    assert.equal((await get(`/v1/vendor/stores/${id}/summary`)).json().available_items, 1);
    assert.equal((await post('/v1/me/devices', { platform: 'web', token: 'web_vendor_test_token_123456789' })).statusCode, 200);
    const image = await post(`/v1/vendor/stores/${id}/media`, { purpose: 'logo', mime: 'image/png', data_base64: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).toString('base64') });
    assert.equal(image.statusCode, 201, image.body);
    await patch(`/v1/vendor/stores/${id}`, { logo_url: image.json().public_url });
    assert.equal((await get(`/v1/vendors/${id}`)).json().vendor.logo_url, image.json().public_url);
    const banner = await post(`/v1/vendor/stores/${id}/media`, { purpose: 'image', mime: 'image/png', data_base64: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).toString('base64') });
    assert.equal(banner.statusCode, 201, banner.body);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { image_url: banner.json().public_url })).statusCode, 200);
    assert.equal((await get(`/v1/vendors/${id}`)).json().vendor.image_url, banner.json().public_url);
    const mealImage = await post(`/v1/vendor/stores/${id}/media`, { purpose: 'image', mime: 'image/png', data_base64: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).toString('base64') });
    assert.equal(mealImage.statusCode, 201, mealImage.body);
    const updatedMeal = await app.inject({ method: 'PUT', url: `/v1/vendor/stores/${id}/menu/${added.json().id}`, headers: h(), payload: menuInputSchema.parse({ name: 'Rice', category: 'Meals', price_kobo: 250000, image_url: mealImage.json().public_url }) });
    assert.equal(updatedMeal.statusCode, 200, updatedMeal.body);
    assert.equal(updatedMeal.json().image_url, mealImage.json().public_url);
    assert.equal((await post(`/v1/vendor/stores/${id}/media`, { purpose: 'image', mime: 'image/png', data_base64: Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).toString('base64') }, 'bob')).statusCode, 404);
    await app.inject({ method: 'PUT', url: `/v1/vendor/stores/${id}/availability`, headers: h(), payload: { is_open: true } });
    const quote = await post('/v1/orders/quote', { type: 'food', vendor_id: id, items: [{ menu_item_id: added.json().id, quantity: 1 }], dropoff: { lat: 10.6, lng: 7.6, address: 'Dropoff' } }, 'bob');
    assert.equal(quote.statusCode, 200, quote.body);
    const booked = await post('/v1/orders', { quote_id: quote.json().id, payment_method: 'wallet' }, 'bob', 'vendor_portal_order');
    assert.equal(booked.statusCode, 201, booked.body);
    const orderId = booked.json().id as string;
    await db.query("UPDATE public.orders SET payment_status='paid',status='awaiting_vendor' WHERE id=$1", [orderId]);
    await db.query("INSERT INTO public.order_events(order_id,actor_id,from_status,to_status,reason)VALUES($1,$2,'pending_payment','awaiting_vendor','test_verified_payment')", [orderId, bob.id]);
    assert.equal((await db.query("SELECT id FROM public.notifications WHERE profile_id=$1 AND kind='vendor_order'", [alice.id])).rows.length, 1);
    const vendorNotice = (await db.query<{
        id: string;
    }>("SELECT id FROM public.notifications WHERE profile_id=$1 AND kind='vendor_order'", [alice.id])).rows[0]!.id;
    const vendorJob = (await notifications.claim(100)).find(j => j.notification_id === vendorNotice && j.channel === 'push')!;
    assert.ok(vendorJob);
    const alert=await notifications.target(vendorJob);assert.equal(alert!.urgent,true);assert.ok(Date.parse(alert!.notification.expires_at!)>Date.now());assert.ok(Date.parse(alert!.notification.expires_at!)<Date.now()+6*60000);
    assert.equal((await get(`/v1/vendor/stores/${id}/orders?status=awaiting_vendor`)).json().length, 1);
    assert.equal((await get(`/v1/vendor/stores/${id}/orders/${orderId}`, 'bob')).statusCode, 404);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { address: 'Moved shop address', location: { lat: 10.51, lng: 7.51 } })).statusCode, 409);
    const accepted = await post(`/v1/vendor/stores/${id}/orders/${orderId}/action`, { action: 'accept', prep_minutes: 30 });
    assert.equal(accepted.statusCode, 200, accepted.body);
    assert.equal((await get(`/v1/vendor/stores/${id}/orders/${orderId}`)).json().vendor_prep_minutes, 30);
    assert.equal((await post(`/v1/vendor/stores/${id}/orders/${orderId}/action`, { action: 'ready' })).statusCode, 200);
    assert.equal((await get(`/v1/vendor/stores/${id}/summary`)).json().ready_orders, 1);
    const portal = await get(`/v1/vendor/stores/${id}/portal`);
    assert.equal(portal.statusCode, 200, portal.body);
    assert.equal(portal.json().dashboard.days.length, 7);
    assert.equal(portal.json().commission_rate, null);
    assert.equal((await get(`/v1/vendor/stores/${id}/portal`, 'bob')).statusCode, 404);
    const hours = Array.from({ length: 7 }, (_, day) => ({ day, open: true, from: '08:00', to: '21:00' }));
    const savedHours = await patch(`/v1/vendor/stores/${id}`, { opening_hours: hours });
    assert.equal(savedHours.statusCode, 200, savedHours.body);
    assert.deepEqual(savedHours.json().opening_hours, hours);
    assert.equal((await patch(`/v1/vendor/stores/${id}`, { opening_hours: hours.map(h => ({...h,day:0})) })).statusCode, 400);
    assert.equal(await notifications.target(vendorJob), null);
    await db.query('UPDATE public.vendors SET is_active=false WHERE id=$1', [id]);
    await assert.rejects(() => accounts.requestDeletion(alice.id, null), /handover/);
    await db.query('UPDATE public.vendors SET is_active=true WHERE id=$1', [id]);
    const other = await submit({ ...input, name: 'Other Kitchen' }, 'bob', 'bob_registration_key');
    const rejected = await review(other.json().id, 'reject');
    assert.equal(rejected.json().vendor_id, null);
    assert.equal((await profiles.bootstrap(bob.id, bob.phone)).role, 'customer');
    assert.equal((await get('/v1/vendor/stores', 'bob')).statusCode, 403);
    const next = await submit(input, 'bob', 'bob_reapplication_key');
    assert.equal(next.statusCode, 201);
    assert.equal((await post(`/v1/vendor/registrations/${next.json().id}/withdraw`, {}, 'alice')).statusCode, 404);
    assert.equal((await post(`/v1/vendor/registrations/${next.json().id}/withdraw`, {}, 'bob')).json().status, 'withdrawn');
    assert.equal((await review(next.json().id)).statusCode, 409);
    await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)", [alice.id]);
    await db.exec('SET ROLE authenticated');
    await assert.rejects(() => db.query('SELECT * FROM vendo_internal.vendor_applications'));
    await assert.rejects(() => db.query("INSERT INTO vendo_internal.vendor_staff(vendor_id,profile_id)VALUES($1,$2)", [id, bob.id]));
    await db.exec('RESET ROLE');
    const preflight = await app.inject({ method: 'OPTIONS', url: '/v1/vendor/stores', headers: { origin: 'https://vendors.example.com', 'access-control-request-method': 'PATCH', 'access-control-request-headers': 'authorization' } });
    assert.equal(preflight.headers['access-control-allow-origin'], 'https://vendors.example.com');
    assert.match(String(preflight.headers['access-control-allow-methods']),/PATCH/);assert.match(String(preflight.headers['access-control-allow-methods']),/PUT/);
});
